// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id",
 *         companyId: "companyId"
 *     }
 */
export interface ListWhopForumsSocialAccountsRequest {
    id: string;
    companyId: string;
}
