// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface NextSlotsSocialAccountsRequest {
    id: string;
    limit?: number;
    after?: string;
}
