// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface UpdateSocialAccountsRequest {
    id: string;
    status?: UpdateSocialAccountsRequest.Status;
}

export namespace UpdateSocialAccountsRequest {
    export const Status = {
        Connected: "connected",
        Disconnected: "disconnected",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
