// This file was auto-generated by Fern from our API Definition.

import { MediaClient } from "./api/resources/media/client/Client.js";
import { PostsClient } from "./api/resources/posts/client/Client.js";
import { SocialAccountsClient } from "./api/resources/socialAccounts/client/Client.js";
import { TagsClient } from "./api/resources/tags/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace SchedulinClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class SchedulinClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<SchedulinClient.Options>;
    protected _posts: PostsClient | undefined;
    protected _socialAccounts: SocialAccountsClient | undefined;
    protected _tags: TagsClient | undefined;
    protected _media: MediaClient | undefined;

    constructor(options: SchedulinClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get posts(): PostsClient {
        return (this._posts ??= new PostsClient(this._options));
    }

    public get socialAccounts(): SocialAccountsClient {
        return (this._socialAccounts ??= new SocialAccountsClient(this._options));
    }

    public get tags(): TagsClient {
        return (this._tags ??= new TagsClient(this._options));
    }

    public get media(): MediaClient {
        return (this._media ??= new MediaClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
                getAuthHeaders: async () => (await this._options.authProvider.getAuthRequest()).headers,
            },
            requestOptions,
        );
    }
}
