// This file was auto-generated by Fern from our API Definition.

export const SchedulinEnvironment = {
    Default: "",
} as const;

export type SchedulinEnvironment = typeof SchedulinEnvironment.Default;
