// This file was auto-generated by Fern from our API Definition.

export const SchedulinEnvironment = {
    Default: "https://api.schedulin.app",
} as const;

export type SchedulinEnvironment = typeof SchedulinEnvironment.Default;
