// This file was auto-generated by Fern from our API Definition.

export interface AiGeneration {
    id: string;
    type: string;
    status: AiGeneration.Status;
    modelKey: string;
    prompt: string;
    imageUrl: string | null;
    resultUrl: string | null;
    width: number | null;
    height: number | null;
    durationSeconds: number | null;
    costMicros: number;
    estimatedCostMicros: number;
    errorMessage: string | null;
    createdAt: string;
    updatedAt: string;
}

export namespace AiGeneration {
    export const Status = {
        Pending: "PENDING",
        Processing: "PROCESSING",
        Completed: "COMPLETED",
        Failed: "FAILED",
        Cancelled: "CANCELLED",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
