// This file was auto-generated by Fern from our API Definition.

export const AnalyticsStatus = {
    Idle: "IDLE",
    Processing: "PROCESSING",
    Failed: "FAILED",
} as const;
export type AnalyticsStatus = (typeof AnalyticsStatus)[keyof typeof AnalyticsStatus];
