// This file was auto-generated by Fern from our API Definition.

/**
 * Error envelope. The machine-readable `code` and HTTP `status` are always present; the human-readable reason is in `message` / `data.message`.
 */
export interface ErrorResponse {
    /** e.g. "BAD_REQUEST", "UNAUTHORIZED", "NOT_FOUND". */
    code: string;
    status: number;
    message?: string | undefined;
    defined?: boolean | undefined;
    data?: ErrorResponse.Data | undefined;
}

export namespace ErrorResponse {
    export interface Data {
        message?: string | undefined;
        /** End-user-safe explanation, when available. */
        userMessage?: string | undefined;
        errorTag?: string | undefined;
        isRetryable?: boolean | undefined;
        /** Accepts any additional properties */
        [key: string]: any;
    }
}
