// This file was auto-generated by Fern from our API Definition.

/**
 * Error envelope. The machine-readable `code` and HTTP `status` are always present; the human-readable reason is in `data.message` (or `data.fieldErrors` for 422 validation errors).
 */
export interface ErrorResponse {
    /** e.g. "BAD_REQUEST", "UNAUTHORIZED", "NOT_FOUND". */
    code: string;
    status: number;
    message?: string | undefined;
    data?: Record<string, unknown> | undefined;
}
