// This file was auto-generated by Fern from our API Definition.

export const ImageProcessingStatus = {
    Pending: "PENDING",
    Processing: "PROCESSING",
    Processed: "PROCESSED",
    Failed: "FAILED",
} as const;
export type ImageProcessingStatus = (typeof ImageProcessingStatus)[keyof typeof ImageProcessingStatus];
