// This file was auto-generated by Fern from our API Definition.

export interface Media {
    id: string;
    url: string;
    name: string;
    mimeType: string;
    width: number | null;
    height: number | null;
    duration: number | null;
    createdAt: string;
    updatedAt: string;
    userId: string;
    bucket: string;
    key: string;
    size: number | null;
}
