// This file was auto-generated by Fern from our API Definition.

export interface MediaUpdate {
    id: string;
    url: string;
    mimeType?: string | undefined;
    width?: number | undefined;
    height?: number | undefined;
    size?: number | undefined;
    duration?: number | undefined;
}
