// This file was auto-generated by Fern from our API Definition.

export interface MediaSearch {
    page?: number | undefined;
    limit?: number | undefined;
    q?: string | undefined;
    type?: MediaSearch.Type | undefined;
    tagIds?: string[] | undefined;
    tagMode?: MediaSearch.TagMode | undefined;
}

export namespace MediaSearch {
    export const Type = {
        Image: "image",
        Video: "video",
        All: "all",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
    export const TagMode = {
        Any: "ANY",
        All: "ALL",
    } as const;
    export type TagMode = (typeof TagMode)[keyof typeof TagMode];
}
