// This file was auto-generated by Fern from our API Definition.

export const OauthScope = {
    /**
     * View posts and drafts */
    PostsRead: "posts:read",
    /**
     * Create, edit, and delete posts */
    PostsWrite: "posts:write",
    /**
     * View tags */
    TagsRead: "tags:read",
    /**
     * Create, edit, and delete tags */
    TagsWrite: "tags:write",
    /**
     * View connected social accounts */
    SocialAccountsRead: "social-accounts:read",
    /**
     * Update and disconnect social accounts */
    SocialAccountsWrite: "social-accounts:write",
    /**
     * View channels */
    ChannelsRead: "channels:read",
    /**
     * View media files */
    MediaRead: "media:read",
    /**
     * Upload and delete media files */
    MediaWrite: "media:write",
    /**
     * View analytics data */
    AnalyticsRead: "analytics:read",
    /**
     * View organization details */
    OrgRead: "org:read",
} as const;
export type OauthScope = (typeof OauthScope)[keyof typeof OauthScope];
