// This file was auto-generated by Fern from our API Definition.

import type * as Schedulin from "../index.js";

export interface Post {
    id: string;
    externalId: string | null;
    caption: string;
    status: Schedulin.PostStatus;
    approvalStatus: Schedulin.PostApprovalStatus;
    approvalRequestedAt: string | null;
    approvalRequestedBy: string | null;
    approvedAt: string | null;
    approvedBy: string | null;
    rejectionReason: string | null;
    scheduledAt: string | null;
    platformConfiguration: Record<string, unknown> | null;
    socialAccountId: string;
    url: string | null;
    createdAt: string;
    updatedAt: string;
}
