// This file was auto-generated by Fern from our API Definition.

import type * as Schedulin from "../index.js";

export interface PostWithRelations {
    id: string;
    externalId: string | null;
    caption: string;
    status: Schedulin.PostStatus;
    approvalStatus: Schedulin.PostApprovalStatus;
    approvalRequestedAt: string | null;
    approvalRequestedBy: string | null;
    approvedAt: string | null;
    approvedBy: string | null;
    rejectionReason: string | null;
    scheduledAt: string | null;
    platformConfiguration: Record<string, unknown> | null;
    socialAccountId: string;
    url: string | null;
    createdAt: string;
    updatedAt: string;
    socialAccount: Schedulin.SocialAccount;
    media: PostWithRelations.Media.Item[];
    tags: Schedulin.Tag[];
}

export namespace PostWithRelations {
    export type Media = Media.Item[];

    export namespace Media {
        export interface Item {
            url: string;
            thumbnail_url?: (string | null) | undefined;
            thumbnail_timestamp_ms?: (number | null) | undefined;
            tags?: Item.Tags.Item[] | undefined;
            alt?: (string | null) | undefined;
            skip_processing?: boolean | undefined;
        }

        export namespace Item {
            export type Tags = Tags.Item[];

            export namespace Tags {
                export interface Item {
                    id: string;
                    type: Item.Type;
                    platform: Item.Platform;
                    x?: number | undefined;
                    y?: number | undefined;
                }

                export namespace Item {
                    export const Type = {
                        User: "user",
                        Business: "business",
                    } as const;
                    export type Type = (typeof Type)[keyof typeof Type];
                    export const Platform = {
                        Bluesky: "bluesky",
                        Facebook: "facebook",
                        GoogleBusinessProfile: "google_business_profile",
                        Instagram: "instagram",
                        Linkedin: "linkedin",
                        Pinterest: "pinterest",
                        Reddit: "reddit",
                        Threads: "threads",
                        Tiktok: "tiktok",
                        Twitter: "twitter",
                        Youtube: "youtube",
                    } as const;
                    export type Platform = (typeof Platform)[keyof typeof Platform];
                }
            }
        }
    }
}
