// This file was auto-generated by Fern from our API Definition.

export interface PostSearch {
    page?: number | undefined;
    status?: PostSearch.Status | undefined;
    approvalStatus?: PostSearch.ApprovalStatus | undefined;
    scheduledAt?: PostSearch.ScheduledAt | undefined;
    tagIds?: string[] | undefined;
    tagMode?: PostSearch.TagMode | undefined;
    socialAccountIds?: string[] | undefined;
    limit?: number | undefined;
}

export namespace PostSearch {
    export const Status = {
        Scheduled: "SCHEDULED",
        Processing: "PROCESSING",
        Completed: "COMPLETED",
        Draft: "DRAFT",
        Failed: "FAILED",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    export const ApprovalStatus = {
        Draft: "DRAFT",
        PendingApproval: "PENDING_APPROVAL",
        Approved: "APPROVED",
        Rejected: "REJECTED",
    } as const;
    export type ApprovalStatus = (typeof ApprovalStatus)[keyof typeof ApprovalStatus];

    export interface ScheduledAt {
        from?: string | undefined;
        to?: string | undefined;
    }

    export const TagMode = {
        Any: "ANY",
        All: "ALL",
    } as const;
    export type TagMode = (typeof TagMode)[keyof typeof TagMode];
}
