// This file was auto-generated by Fern from our API Definition.

export const PostApprovalStatus = {
    Draft: "DRAFT",
    PendingApproval: "PENDING_APPROVAL",
    Approved: "APPROVED",
    Rejected: "REJECTED",
} as const;
export type PostApprovalStatus = (typeof PostApprovalStatus)[keyof typeof PostApprovalStatus];
