// This file was auto-generated by Fern from our API Definition.

import type * as Schedulin from "../index.js";

export interface PostWithRelations {
    id: string;
    externalId: string | null;
    caption: string;
    status: Schedulin.PostStatus;
    approvalStatus: Schedulin.PostApprovalStatus;
    approvalRequestedAt: string | null;
    approvalRequestedBy: string | null;
    approvedAt: string | null;
    approvedBy: string | null;
    rejectionReason: string | null;
    scheduledAt: string | null;
    platformConfiguration?: (PostWithRelations.PlatformConfiguration | null) | undefined;
    socialAccountId: string;
    url: string | null;
    createdAt: string;
    updatedAt: string;
    socialAccount: PostWithRelations.SocialAccount;
    media: PostWithRelations.Media.Item[];
    tags: Schedulin.Tag[];
}

export namespace PostWithRelations {
    export type PlatformConfiguration =
        | unknown
        | {
              caption?: (string | null) | undefined;
              media?:
                  | {
                        url: string;
                        thumbnail_url?: (string | null) | undefined;
                        thumbnail_timestamp_ms?: (number | null) | undefined;
                        tags?:
                            | {
                                  id: string;
                                  type: "user" | "business";
                                  platform:
                                      | "bluesky"
                                      | "facebook"
                                      | "instagram"
                                      | "linkedin"
                                      | "pinterest"
                                      | "threads"
                                      | "tiktok"
                                      | "twitter"
                                      | "youtube";
                                  x?: number | undefined;
                                  y?: number | undefined;
                              }[]
                            | undefined;
                        alt?: (string | null) | undefined;
                        skip_processing?: boolean | undefined;
                    }[]
                  | undefined;
              placement?: ("feed" | "reels" | "stories") | undefined;
              collaborators?: string[] | undefined;
              share_to_feed?: boolean | undefined;
              location?: (string | null) | undefined;
              trial_reel_type?: ("manual" | "auto") | undefined;
              music?: (string | null) | undefined;
              tagged_products?: (string | null) | undefined;
              first_comment?: (string | null) | undefined;
              notify_me?: boolean | undefined;
              is_paid_partnership?: boolean | undefined;
              branded_content_sponsor_ids?: string[] | undefined;
          }
        | {
              caption?: (string | null) | undefined;
              media?:
                  | {
                        url: string;
                        thumbnail_url?: (string | null) | undefined;
                        thumbnail_timestamp_ms?: (number | null) | undefined;
                        tags?:
                            | {
                                  id: string;
                                  type: "user" | "business";
                                  platform:
                                      | "bluesky"
                                      | "facebook"
                                      | "instagram"
                                      | "linkedin"
                                      | "pinterest"
                                      | "threads"
                                      | "tiktok"
                                      | "twitter"
                                      | "youtube";
                                  x?: number | undefined;
                                  y?: number | undefined;
                              }[]
                            | undefined;
                        alt?: (string | null) | undefined;
                        skip_processing?: boolean | undefined;
                    }[]
                  | undefined;
              title?: (string | null) | undefined;
              description?: (string | null) | undefined;
              photo_cover_index?: number | undefined;
              privacy_status?:
                  | (
                        | "public"
                        | "private"
                        | "friends"
                        | "mutual_follow_friends"
                        | "follower_of_creator"
                        | "self_only"
                        | "PUBLIC_TO_EVERYONE"
                    )
                  | undefined;
              allow_comment?: boolean | undefined;
              allow_duet?: boolean | undefined;
              allow_stitch?: boolean | undefined;
              disclose_your_brand?: boolean | undefined;
              disclose_branded_content?: boolean | undefined;
              disclose_video_content?: boolean | undefined;
              is_ai_generated?: boolean | undefined;
              is_draft?: boolean | undefined;
              auto_add_music?: boolean | undefined;
          }
        | {
              caption?: (string | null) | undefined;
              media?:
                  | {
                        url: string;
                        thumbnail_url?: (string | null) | undefined;
                        thumbnail_timestamp_ms?: (number | null) | undefined;
                        tags?:
                            | {
                                  id: string;
                                  type: "user" | "business";
                                  platform:
                                      | "bluesky"
                                      | "facebook"
                                      | "instagram"
                                      | "linkedin"
                                      | "pinterest"
                                      | "threads"
                                      | "tiktok"
                                      | "twitter"
                                      | "youtube";
                                  x?: number | undefined;
                                  y?: number | undefined;
                              }[]
                            | undefined;
                        alt?: (string | null) | undefined;
                        skip_processing?: boolean | undefined;
                    }[]
                  | undefined;
              poll?:
                  | {
                        duration_minutes: number;
                        options: string[];
                        reply_settings?: ("everyone" | "following" | "mentioned") | undefined;
                    }
                  | undefined;
              community_id?: string | undefined;
              community_name?: string | undefined;
              quote_tweet_id?: string | undefined;
              in_reply_to_tweet_id?: string | undefined;
              geo?:
                  | {
                        place_id: string;
                    }
                  | undefined;
              reply_settings?: ("everyone" | "following" | "mentioned") | undefined;
          }
        | {
              caption?: (string | null) | undefined;
              media?:
                  | {
                        url: string;
                        thumbnail_url?: (string | null) | undefined;
                        thumbnail_timestamp_ms?: (number | null) | undefined;
                        tags?:
                            | {
                                  id: string;
                                  type: "user" | "business";
                                  platform:
                                      | "bluesky"
                                      | "facebook"
                                      | "instagram"
                                      | "linkedin"
                                      | "pinterest"
                                      | "threads"
                                      | "tiktok"
                                      | "twitter"
                                      | "youtube";
                                  x?: number | undefined;
                                  y?: number | undefined;
                              }[]
                            | undefined;
                        alt?: (string | null) | undefined;
                        skip_processing?: boolean | undefined;
                    }[]
                  | undefined;
              title: string;
              categoryId: string;
              visibility: "public" | "unlisted" | "private";
              license?: ("standard" | "creative_commons" | "youtube" | "creativeCommon") | undefined;
              notifySubscribers?: boolean | undefined;
              allowEmbedding?: boolean | undefined;
              madeForKids?: boolean | undefined;
              tags?: string[] | undefined;
              defaultLanguage?: (string | null) | undefined;
              defaultAudioLanguage?: (string | null) | undefined;
              recordingDate?: (string | null) | undefined;
              publishAt?: (string | null) | undefined;
              containsSyntheticMedia?: boolean | undefined;
              publicStatsViewable?: boolean | undefined;
          }
        | {
              caption?: (string | null) | undefined;
              media?:
                  | {
                        url: string;
                        thumbnail_url?: (string | null) | undefined;
                        thumbnail_timestamp_ms?: (number | null) | undefined;
                        tags?:
                            | {
                                  id: string;
                                  type: "user" | "business";
                                  platform:
                                      | "bluesky"
                                      | "facebook"
                                      | "instagram"
                                      | "linkedin"
                                      | "pinterest"
                                      | "threads"
                                      | "tiktok"
                                      | "twitter"
                                      | "youtube";
                                  x?: number | undefined;
                                  y?: number | undefined;
                              }[]
                            | undefined;
                        alt?: (string | null) | undefined;
                        skip_processing?: boolean | undefined;
                    }[]
                  | undefined;
              placement?: ("feed" | "reels" | "stories") | undefined;
              location?: (string | null) | undefined;
              collaborators?: string[] | undefined;
              first_comment?: (string | null) | undefined;
              tagged_users?: string[] | undefined;
              scheduled_publish_time?: number | undefined;
              feed_targeting?: Record<string, unknown> | undefined;
              targeting?: Record<string, unknown> | undefined;
          }
        | {
              caption?: (string | null) | undefined;
              media?:
                  | {
                        url: string;
                        thumbnail_url?: (string | null) | undefined;
                        thumbnail_timestamp_ms?: (number | null) | undefined;
                        tags?:
                            | {
                                  id: string;
                                  type: "user" | "business";
                                  platform:
                                      | "bluesky"
                                      | "facebook"
                                      | "instagram"
                                      | "linkedin"
                                      | "pinterest"
                                      | "threads"
                                      | "tiktok"
                                      | "twitter"
                                      | "youtube";
                                  x?: number | undefined;
                                  y?: number | undefined;
                              }[]
                            | undefined;
                        alt?: (string | null) | undefined;
                        skip_processing?: boolean | undefined;
                    }[]
                  | undefined;
              visibility?: ("PUBLIC" | "CONNECTIONS" | "LOGGED_IN" | "CONTAINER") | undefined;
              alt_text?: (string | null) | undefined;
              first_comment?: (string | null) | undefined;
              author_kind?: ("person" | "organization") | undefined;
              organization_id?: string | undefined;
              reshare_disabled?: boolean | undefined;
              article?:
                  | {
                        source: string;
                        title: string;
                        description?: string | undefined;
                        thumbnail_url?: string | undefined;
                    }
                  | undefined;
              poll?:
                  | {
                        question: string;
                        options: string[];
                        duration?: ("ONE_DAY" | "THREE_DAYS" | "SEVEN_DAYS" | "FOURTEEN_DAYS") | undefined;
                    }
                  | undefined;
              multi_image_alt_text?: (string | null)[] | undefined;
              target_entities?:
                  | {
                        locales?: string[] | undefined;
                        industries?: string[] | undefined;
                        seniorities?: string[] | undefined;
                        functions?: string[] | undefined;
                        staffCountRanges?: string[] | undefined;
                        followedCompanies?: string[] | undefined;
                    }[]
                  | undefined;
          }
        | {
              caption?: (string | null) | undefined;
              media?:
                  | {
                        url: string;
                        thumbnail_url?: (string | null) | undefined;
                        thumbnail_timestamp_ms?: (number | null) | undefined;
                        tags?:
                            | {
                                  id: string;
                                  type: "user" | "business";
                                  platform:
                                      | "bluesky"
                                      | "facebook"
                                      | "instagram"
                                      | "linkedin"
                                      | "pinterest"
                                      | "threads"
                                      | "tiktok"
                                      | "twitter"
                                      | "youtube";
                                  x?: number | undefined;
                                  y?: number | undefined;
                              }[]
                            | undefined;
                        alt?: (string | null) | undefined;
                        skip_processing?: boolean | undefined;
                    }[]
                  | undefined;
              alt_text?: (string | null)[] | undefined;
              langs?: string[] | undefined;
              external?:
                  | {
                        uri: string;
                        title?: string | undefined;
                        description?: string | undefined;
                        thumb_url?: string | undefined;
                    }
                  | undefined;
              quote_post_uri?: string | undefined;
              reply_to?:
                  | {
                        root: string;
                        parent?: string | undefined;
                    }
                  | undefined;
              threadgate?:
                  | {
                        allow?: (unknown | null)[] | undefined;
                        hidden_replies?: string[] | undefined;
                    }
                  | undefined;
              postgate?:
                  | {
                        embedding_disabled?: boolean | undefined;
                        detached_embedding_uris?: string[] | undefined;
                    }
                  | undefined;
              labels?: string[] | undefined;
          }
        | {
              caption?: (string | null) | undefined;
              media?:
                  | {
                        url: string;
                        thumbnail_url?: (string | null) | undefined;
                        thumbnail_timestamp_ms?: (number | null) | undefined;
                        tags?:
                            | {
                                  id: string;
                                  type: "user" | "business";
                                  platform:
                                      | "bluesky"
                                      | "facebook"
                                      | "instagram"
                                      | "linkedin"
                                      | "pinterest"
                                      | "threads"
                                      | "tiktok"
                                      | "twitter"
                                      | "youtube";
                                  x?: number | undefined;
                                  y?: number | undefined;
                              }[]
                            | undefined;
                        alt?: (string | null) | undefined;
                        skip_processing?: boolean | undefined;
                    }[]
                  | undefined;
              placement?: ("feed" | "reels") | undefined;
              post_type?: ("thread" | "ghost_post") | undefined;
              reply_control?:
                  | (
                        | "everyone"
                        | "accounts_you_follow"
                        | "mentioned_only"
                        | "parent_post_author_only"
                        | "followers_only"
                    )
                  | undefined;
              topic?: (string | null) | undefined;
              topic_tag?: (string | null) | undefined;
              location?: (string | null) | undefined;
              location_id?: (string | null) | undefined;
              quote_post_id?: string | undefined;
              reply_to_id?: string | undefined;
              link_attachment?: string | undefined;
              allowlisted_country_codes?: string[] | undefined;
              poll?:
                  | {
                        question?: string | undefined;
                        options: string[];
                    }
                  | undefined;
              gif?:
                  | {
                        gif_id: string;
                        gif_provider?: "GIPHY" | undefined;
                    }
                  | undefined;
          };

    export interface SocialAccount {
        id: string;
        platform: Schedulin.SocialPlatform;
        username: string | null;
        imageUrl: string | null;
    }

    export type Media = Media.Item[];

    export namespace Media {
        export interface Item {
            url: string;
            thumbnail_url?: (string | null) | undefined;
            thumbnail_timestamp_ms?: (number | null) | undefined;
            tags?: Item.Tags.Item[] | undefined;
            alt?: (string | null) | undefined;
            skip_processing?: boolean | undefined;
        }

        export namespace Item {
            export type Tags = Tags.Item[];

            export namespace Tags {
                export interface Item {
                    id: string;
                    type: Item.Type;
                    platform: Item.Platform;
                    x?: number | undefined;
                    y?: number | undefined;
                }

                export namespace Item {
                    export const Type = {
                        User: "user",
                        Business: "business",
                    } as const;
                    export type Type = (typeof Type)[keyof typeof Type];
                    export const Platform = {
                        Bluesky: "bluesky",
                        Facebook: "facebook",
                        Instagram: "instagram",
                        Linkedin: "linkedin",
                        Pinterest: "pinterest",
                        Threads: "threads",
                        Tiktok: "tiktok",
                        Twitter: "twitter",
                        Youtube: "youtube",
                    } as const;
                    export type Platform = (typeof Platform)[keyof typeof Platform];
                }
            }
        }
    }
}
