// This file was auto-generated by Fern from our API Definition.

import type * as Schedulin from "../index.js";

export interface PostThreadPart {
    caption: string;
    media: Schedulin.PostMedia[];
}
