// This file was auto-generated by Fern from our API Definition.

export interface PostMedia {
    id: string;
    url: string;
    name: string;
    mimeType: string;
    width: number | null;
    height: number | null;
    duration: number | null;
    size: number | null;
    alt: string | null;
    thumbnailUrl: string | null;
    createdAt: string;
    updatedAt: string;
}
