// This file was auto-generated by Fern from our API Definition.

export const PostStatus = {
    Scheduled: "SCHEDULED",
    Processing: "PROCESSING",
    Completed: "COMPLETED",
    Draft: "DRAFT",
    Failed: "FAILED",
} as const;
export type PostStatus = (typeof PostStatus)[keyof typeof PostStatus];
