// This file was auto-generated by Fern from our API Definition.

export interface PresignedPost {
    url: string;
    key: string;
    method: PresignedPost.Method;
}

export namespace PresignedPost {
    export const Method = {
        Put: "PUT",
    } as const;
    export type Method = (typeof Method)[keyof typeof Method];
}
