// This file was auto-generated by Fern from our API Definition.

/**
 * 429 rate-limit error. Per-key request limits return `code: "RATE_LIMITED"` (also mirrored under `error`); the per-user limiter returns `code: "TOO_MANY_REQUESTS"`. Honor the `Retry-After` header.
 */
export interface RateLimitErrorResponse {
    code: string;
    status: number;
    message?: string | undefined;
    defined?: boolean | undefined;
    data?: Record<string, unknown> | undefined;
    error?: RateLimitErrorResponse.Error_ | undefined;
}

export namespace RateLimitErrorResponse {
    export interface Error_ {
        code: string;
        message: string;
    }
}
