// This file was auto-generated by Fern from our API Definition.

import type * as Schedulin from "../index.js";

export interface SocialAccountPublic {
    id: string;
    platform: Schedulin.SocialPlatform;
    username: string | null;
    user_id: string;
    profile_photo_url: string | null;
    status: SocialAccountPublic.Status;
    external_id: string | null;
}

export namespace SocialAccountPublic {
    export const Status = {
        Connected: "connected",
        Disconnected: "disconnected",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
