// This file was auto-generated by Fern from our API Definition.

export interface SocialAccountUpdate {
    id: string;
    status?: SocialAccountUpdate.Status | undefined;
}

export namespace SocialAccountUpdate {
    export const Status = {
        Connected: "connected",
        Disconnected: "disconnected",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
