// This file was auto-generated by Fern from our API Definition.

export const SocialPlatform = {
    Bluesky: "bluesky",
    Facebook: "facebook",
    Instagram: "instagram",
    Linkedin: "linkedin",
    Pinterest: "pinterest",
    Threads: "threads",
    Tiktok: "tiktok",
    Twitter: "twitter",
    Youtube: "youtube",
} as const;
export type SocialPlatform = (typeof SocialPlatform)[keyof typeof SocialPlatform];
