// This file was auto-generated by Fern from our API Definition.

import type * as Schedulin from "../index.js";

export interface SocialAccount {
    id: string;
    platform: Schedulin.SocialPlatform;
    imageUrl: string | null;
    imageProcessingStatus: Schedulin.ImageProcessingStatus;
    username: string | null;
    status: SocialAccount.Status;
    disconnectedReason: Schedulin.SocialAccountDisconnectedReason | null;
    createdAt: string;
    updatedAt: string;
    refreshTokenValid: boolean;
}

export namespace SocialAccount {
    export const Status = {
        Connected: "connected",
        Disconnected: "disconnected",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
