// This file was auto-generated by Fern from our API Definition.

export interface SocialAccountUpdate {
    platform?: SocialAccountUpdate.Platform | undefined;
    accessToken?: string | undefined;
    secretAccessToken?: (string | null) | undefined;
    refreshToken?: (string | null) | undefined;
    refreshTokenValid?: boolean | undefined;
    tokenExpiresAt?: (string | null) | undefined;
    imageUrl?: string | undefined;
    imageProcessingStatus?: SocialAccountUpdate.ImageProcessingStatus | undefined;
    platformData?: Record<string, unknown> | undefined;
    lastRefreshAt?: string | undefined;
    status?: SocialAccountUpdate.Status | undefined;
    id: string;
}

export namespace SocialAccountUpdate {
    export const Platform = {
        Bluesky: "bluesky",
        Facebook: "facebook",
        Instagram: "instagram",
        Linkedin: "linkedin",
        Pinterest: "pinterest",
        Threads: "threads",
        Tiktok: "tiktok",
        Twitter: "twitter",
        Youtube: "youtube",
    } as const;
    export type Platform = (typeof Platform)[keyof typeof Platform];
    export const ImageProcessingStatus = {
        Pending: "PENDING",
        Processing: "PROCESSING",
        Processed: "PROCESSED",
        Failed: "FAILED",
    } as const;
    export type ImageProcessingStatus = (typeof ImageProcessingStatus)[keyof typeof ImageProcessingStatus];
    export const Status = {
        Connected: "connected",
        Disconnected: "disconnected",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
