// This file was auto-generated by Fern from our API Definition.

export const SocialAccountDisconnectedReason = {
    TokenExpired: "TOKEN_EXPIRED",
    TokenInvalid: "TOKEN_INVALID",
    TokenRevoked: "TOKEN_REVOKED",
    RefreshFailed: "REFRESH_FAILED",
    AccountSuspended: "ACCOUNT_SUSPENDED",
    PermissionDenied: "PERMISSION_DENIED",
    EmailUnconfirmed: "EMAIL_UNCONFIRMED",
} as const;
export type SocialAccountDisconnectedReason =
    (typeof SocialAccountDisconnectedReason)[keyof typeof SocialAccountDisconnectedReason];
