// This file was auto-generated by Fern from our API Definition.

export interface Tag {
    id: string;
    userId: string;
    name: string;
    color: string;
    createdAt: string;
    updatedAt: string;
}
