// This file was auto-generated by Fern from our API Definition.

/**
 * 422 error. `data.fieldErrors` maps each invalid field to its messages; `data.formErrors` holds errors not tied to one field. `code` is "INPUT_VALIDATION_FAILED" for schema validation and "UNPROCESSABLE_CONTENT" for business-rule rejections, whose reason is also in `data.message`.
 */
export interface ValidationErrorResponse {
    /** "INPUT_VALIDATION_FAILED" or "UNPROCESSABLE_CONTENT" */
    code: string;
    status: number;
    message?: string | undefined;
    defined?: boolean | undefined;
    data: ValidationErrorResponse.Data;
}

export namespace ValidationErrorResponse {
    export interface Data {
        /** Human-readable reason (business-rule rejections only). */
        message?: string | undefined;
        formErrors?: string[] | undefined;
        fieldErrors?: Record<string, string[]> | undefined;
    }
}
