// This file was auto-generated by Fern from our API Definition.

/**
 * 422 input validation error. `data.fieldErrors` maps each invalid field to its messages; `data.formErrors` holds errors not tied to one field.
 */
export interface ValidationErrorResponse {
    /** "INPUT_VALIDATION_FAILED" */
    code: string;
    status: number;
    message?: string | undefined;
    defined?: boolean | undefined;
    data: ValidationErrorResponse.Data;
}

export namespace ValidationErrorResponse {
    export interface Data {
        formErrors?: string[] | undefined;
        fieldErrors?: Record<string, string[]> | undefined;
    }
}
