// This file was auto-generated by Fern from our API Definition.

export interface WebhookEndpoint {
    id: string;
    url: string;
    secret: string;
    events: WebhookEndpoint.Events.Item[];
    description: string | null;
    enabled: boolean;
    consecutiveFailures: number;
    lastSuccessAt: string | null;
    lastFailureAt: string | null;
    disabledAt: string | null;
    createdAt: string;
    updatedAt: string;
}

export namespace WebhookEndpoint {
    export type Events = Events.Item[];

    export namespace Events {
        export const Item = {
            PostPublished: "post.published",
            PostFailed: "post.failed",
            GenerationCompleted: "generation.completed",
            GenerationFailed: "generation.failed",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }
}
