// This file was auto-generated by Fern from our API Definition.

export interface WebhookDelivery {
    id: string;
    endpointId: string;
    event: string;
    payload: Record<string, unknown>;
    status: WebhookDelivery.Status;
    attempts: number;
    responseStatus: number | null;
    lastError: string | null;
    deliveredAt: string | null;
    createdAt: string;
}

export namespace WebhookDelivery {
    export const Status = {
        Pending: "PENDING",
        Success: "SUCCESS",
        Failed: "FAILED",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
