// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Schedulin from "../../../index.js";

export declare namespace PostsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class PostsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<PostsClient.Options>;

    constructor(options: PostsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Search and filter posts with various criteria including status, date range, social accounts, and tags
     *
     * @param {Schedulin.ListPostsRequest} request
     * @param {PostsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.InternalServerError}
     *
     * @example
     *     await client.posts.list()
     */
    public list(
        request: Schedulin.ListPostsRequest = {},
        requestOptions?: PostsClient.RequestOptions,
    ): core.HttpResponsePromise<Schedulin.ListPostsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__list(request, requestOptions));
    }

    private async __list(
        request: Schedulin.ListPostsRequest = {},
        requestOptions?: PostsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Schedulin.ListPostsResponse>> {
        const { page, status, approvalStatus, scheduledAt, tagIds, tagMode, socialAccountIds, limit } = request;
        const _queryParams: Record<string, unknown> = {
            page,
            status: status != null ? status : undefined,
            approvalStatus: approvalStatus != null ? approvalStatus : undefined,
            scheduledAt,
            tagIds,
            tagMode: tagMode != null ? tagMode : undefined,
            socialAccountIds,
            limit,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                "v0/posts",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Schedulin.ListPostsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v0/posts");
    }

    /**
     * Create a new post with media, tags, and scheduling options
     *
     * @param {Schedulin.PostCreate} request
     * @param {PostsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.InternalServerError}
     *
     * @example
     *     await client.posts.create({
     *         caption: "caption",
     *         socialAccountId: "socialAccountId"
     *     })
     */
    public create(
        request: Schedulin.PostCreate,
        requestOptions?: PostsClient.RequestOptions,
    ): core.HttpResponsePromise<Schedulin.CreatePostsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: Schedulin.PostCreate,
        requestOptions?: PostsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Schedulin.CreatePostsResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                "v0/posts",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Schedulin.CreatePostsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v0/posts");
    }

    /**
     * Returns counts of posts for the Queue, Drafts, Approvals, and Sent tabs
     *
     * @param {Schedulin.V0PostCountByTabRequest} request
     * @param {PostsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.InternalServerError}
     *
     * @example
     *     await client.posts.v0PostCountByTab()
     */
    public v0PostCountByTab(
        request: Schedulin.V0PostCountByTabRequest = {},
        requestOptions?: PostsClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__v0PostCountByTab(request, requestOptions));
    }

    private async __v0PostCountByTab(
        request: Schedulin.V0PostCountByTabRequest = {},
        requestOptions?: PostsClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { socialAccountIds } = request;
        const _queryParams: Record<string, unknown> = {
            socialAccountIds,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                "v0/posts/counts/by-tab",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v0/posts/counts/by-tab");
    }

    /**
     * Retrieve a single post by its ID with all relations
     *
     * @param {Schedulin.RetrievePostsRequest} request
     * @param {PostsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.InternalServerError}
     *
     * @example
     *     await client.posts.retrieve({
     *         id: "id"
     *     })
     */
    public retrieve(
        request: Schedulin.RetrievePostsRequest,
        requestOptions?: PostsClient.RequestOptions,
    ): core.HttpResponsePromise<Schedulin.PostWithRelations> {
        return core.HttpResponsePromise.fromPromise(this.__retrieve(request, requestOptions));
    }

    private async __retrieve(
        request: Schedulin.RetrievePostsRequest,
        requestOptions?: PostsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Schedulin.PostWithRelations>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                `v0/posts/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Schedulin.PostWithRelations, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v0/posts/{id}");
    }

    /**
     * Update an existing post by its ID
     *
     * @param {Schedulin.UpdatePostsRequest} request
     * @param {PostsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.InternalServerError}
     *
     * @example
     *     await client.posts.update({
     *         id: "id"
     *     })
     */
    public update(
        request: Schedulin.UpdatePostsRequest,
        requestOptions?: PostsClient.RequestOptions,
    ): core.HttpResponsePromise<Schedulin.Post> {
        return core.HttpResponsePromise.fromPromise(this.__update(request, requestOptions));
    }

    private async __update(
        request: Schedulin.UpdatePostsRequest,
        requestOptions?: PostsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Schedulin.Post>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                `v0/posts/${core.url.encodePathParam(id)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Schedulin.Post, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PUT", "/v0/posts/{id}");
    }

    /**
     * Delete a post by its ID
     *
     * @param {Schedulin.DeletePostsRequest} request
     * @param {PostsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.InternalServerError}
     *
     * @example
     *     await client.posts.delete({
     *         id: "id"
     *     })
     */
    public delete(
        request: Schedulin.DeletePostsRequest,
        requestOptions?: PostsClient.RequestOptions,
    ): core.HttpResponsePromise<Schedulin.Post> {
        return core.HttpResponsePromise.fromPromise(this.__delete(request, requestOptions));
    }

    private async __delete(
        request: Schedulin.DeletePostsRequest,
        requestOptions?: PostsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Schedulin.Post>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                `v0/posts/${core.url.encodePathParam(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Schedulin.Post, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/v0/posts/{id}");
    }

    /**
     * Retrieve the latest analytics snapshot for a post
     *
     * @param {Schedulin.AnalyticsSummaryPostsRequest} request
     * @param {PostsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.InternalServerError}
     *
     * @example
     *     await client.posts.analyticsSummary({
     *         id: "id"
     *     })
     */
    public analyticsSummary(
        request: Schedulin.AnalyticsSummaryPostsRequest,
        requestOptions?: PostsClient.RequestOptions,
    ): core.HttpResponsePromise<Schedulin.AnalyticsSummaryPostsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__analyticsSummary(request, requestOptions));
    }

    private async __analyticsSummary(
        request: Schedulin.AnalyticsSummaryPostsRequest,
        requestOptions?: PostsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Schedulin.AnalyticsSummaryPostsResponse>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                `v0/posts/${core.url.encodePathParam(id)}/analytics/summary`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Schedulin.AnalyticsSummaryPostsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v0/posts/{id}/analytics/summary",
        );
    }

    /**
     * Retrieve time series analytics metrics for a post
     *
     * @param {Schedulin.AnalyticsSeriesPostsRequest} request
     * @param {PostsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.InternalServerError}
     *
     * @example
     *     await client.posts.analyticsSeries({
     *         id: "id"
     *     })
     */
    public analyticsSeries(
        request: Schedulin.AnalyticsSeriesPostsRequest,
        requestOptions?: PostsClient.RequestOptions,
    ): core.HttpResponsePromise<Schedulin.AnalyticsSeriesPostsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__analyticsSeries(request, requestOptions));
    }

    private async __analyticsSeries(
        request: Schedulin.AnalyticsSeriesPostsRequest,
        requestOptions?: PostsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Schedulin.AnalyticsSeriesPostsResponse>> {
        const { id, limit } = request;
        const _queryParams: Record<string, unknown> = {
            limit,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                `v0/posts/${core.url.encodePathParam(id)}/analytics/series`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Schedulin.AnalyticsSeriesPostsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v0/posts/{id}/analytics/series",
        );
    }

    /**
     * Publish a draft post to connected social media accounts
     *
     * @param {Schedulin.PublishDraftPostsRequest} request
     * @param {PostsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.InternalServerError}
     *
     * @example
     *     await client.posts.publishDraft({
     *         id: "id"
     *     })
     */
    public publishDraft(
        request: Schedulin.PublishDraftPostsRequest,
        requestOptions?: PostsClient.RequestOptions,
    ): core.HttpResponsePromise<Schedulin.Post> {
        return core.HttpResponsePromise.fromPromise(this.__publishDraft(request, requestOptions));
    }

    private async __publishDraft(
        request: Schedulin.PublishDraftPostsRequest,
        requestOptions?: PostsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Schedulin.Post>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                `v0/posts/${core.url.encodePathParam(id)}/publish`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Schedulin.Post, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v0/posts/{id}/publish");
    }

    /**
     * Replace all tags on a post. No status restrictions apply.
     *
     * @param {Schedulin.UpdateTagsPostsRequest} request
     * @param {PostsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.InternalServerError}
     *
     * @example
     *     await client.posts.updateTags({
     *         id: "id",
     *         tagIds: ["tagIds"]
     *     })
     */
    public updateTags(
        request: Schedulin.UpdateTagsPostsRequest,
        requestOptions?: PostsClient.RequestOptions,
    ): core.HttpResponsePromise<Schedulin.Post> {
        return core.HttpResponsePromise.fromPromise(this.__updateTags(request, requestOptions));
    }

    private async __updateTags(
        request: Schedulin.UpdateTagsPostsRequest,
        requestOptions?: PostsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Schedulin.Post>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                `v0/posts/${core.url.encodePathParam(id)}/tags`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Schedulin.Post, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PUT", "/v0/posts/{id}/tags");
    }

    /**
     * Retrieve the processing job status and logs for a post
     *
     * @param {Schedulin.GetJobStatusPostsRequest} request
     * @param {PostsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.InternalServerError}
     *
     * @example
     *     await client.posts.getJobStatus({
     *         id: "id"
     *     })
     */
    public getJobStatus(
        request: Schedulin.GetJobStatusPostsRequest,
        requestOptions?: PostsClient.RequestOptions,
    ): core.HttpResponsePromise<unknown | null> {
        return core.HttpResponsePromise.fromPromise(this.__getJobStatus(request, requestOptions));
    }

    private async __getJobStatus(
        request: Schedulin.GetJobStatusPostsRequest,
        requestOptions?: PostsClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown | null>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                `v0/posts/${core.url.encodePathParam(id)}/jobs`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as unknown | null, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v0/posts/{id}/jobs");
    }
}
