// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Schedulin from "../../../index.js";

export declare namespace PostsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class PostsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<PostsClient.Options>;

    constructor(options: PostsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Search and filter posts with various criteria including status, date range, social accounts, and tags
     *
     * @param {Schedulin.ListPostsRequest} request
     * @param {PostsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.BadRequestError}
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.ForbiddenError}
     * @throws {@link Schedulin.UnprocessableEntityError}
     * @throws {@link Schedulin.TooManyRequestsError}
     * @throws {@link Schedulin.InternalServerError}
     * @throws {@link errors.SchedulinError}
     * @throws {@link errors.SchedulinTimeoutError}
     *
     * @example
     *     await client.posts.list()
     */
    public list(
        request: Schedulin.ListPostsRequest = {},
        requestOptions?: PostsClient.RequestOptions,
    ): core.HttpResponsePromise<Schedulin.ListPostsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__list(request, requestOptions));
    }

    private async __list(
        request: Schedulin.ListPostsRequest = {},
        requestOptions?: PostsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Schedulin.ListPostsResponse>> {
        const { page, status, statuses, approvalStatus, scheduledAt, tagIds, tagMode, socialAccountIds, limit } =
            request;
        const _queryParams: Record<string, unknown> = {
            page,
            status: status != null ? status : undefined,
            statuses: Array.isArray(statuses) ? statuses.map((item) => item) : statuses != null ? statuses : undefined,
            approvalStatus: approvalStatus != null ? approvalStatus : undefined,
            scheduledAt,
            tagIds,
            tagMode: tagMode != null ? tagMode : undefined,
            socialAccountIds,
            limit,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                "v0/posts",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Schedulin.ListPostsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Schedulin.BadRequestError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Schedulin.ForbiddenError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new Schedulin.UnprocessableEntityError(
                        _response.error.body as Schedulin.ValidationErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Schedulin.TooManyRequestsError(
                        _response.error.body as Schedulin.RateLimitErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v0/posts");
    }

    /**
     * Create a new post with media, tags, and scheduling options. Media items may reference a stored library URL or any publicly reachable image/video URL — external URLs are downloaded into the media library automatically, so clients that cannot issue a raw presigned PUT can attach media in one call.
     *
     * @param {Schedulin.PostCreate} request
     * @param {PostsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.BadRequestError}
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.PaymentRequiredError}
     * @throws {@link Schedulin.ForbiddenError}
     * @throws {@link Schedulin.NotFoundError}
     * @throws {@link Schedulin.ConflictError}
     * @throws {@link Schedulin.UnprocessableEntityError}
     * @throws {@link Schedulin.TooManyRequestsError}
     * @throws {@link Schedulin.InternalServerError}
     * @throws {@link errors.SchedulinError}
     * @throws {@link errors.SchedulinTimeoutError}
     *
     * @example
     *     await client.posts.create({
     *         caption: "caption",
     *         socialAccountId: "socialAccountId"
     *     })
     */
    public create(
        request: Schedulin.PostCreate,
        requestOptions?: PostsClient.RequestOptions,
    ): core.HttpResponsePromise<Schedulin.CreatePostsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: Schedulin.PostCreate,
        requestOptions?: PostsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Schedulin.CreatePostsResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                "v0/posts",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Schedulin.CreatePostsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Schedulin.BadRequestError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 402:
                    throw new Schedulin.PaymentRequiredError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Schedulin.ForbiddenError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Schedulin.NotFoundError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new Schedulin.ConflictError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new Schedulin.UnprocessableEntityError(
                        _response.error.body as Schedulin.ValidationErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Schedulin.TooManyRequestsError(
                        _response.error.body as Schedulin.RateLimitErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v0/posts");
    }

    /**
     * Returns counts of posts for the Queue, Drafts, Approvals, and Sent tabs
     *
     * @param {Schedulin.CountByTabPostsRequest} request
     * @param {PostsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.BadRequestError}
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.ForbiddenError}
     * @throws {@link Schedulin.UnprocessableEntityError}
     * @throws {@link Schedulin.TooManyRequestsError}
     * @throws {@link Schedulin.InternalServerError}
     * @throws {@link errors.SchedulinError}
     * @throws {@link errors.SchedulinTimeoutError}
     *
     * @example
     *     await client.posts.countByTab()
     */
    public countByTab(
        request: Schedulin.CountByTabPostsRequest = {},
        requestOptions?: PostsClient.RequestOptions,
    ): core.HttpResponsePromise<Schedulin.CountByTabPostsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__countByTab(request, requestOptions));
    }

    private async __countByTab(
        request: Schedulin.CountByTabPostsRequest = {},
        requestOptions?: PostsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Schedulin.CountByTabPostsResponse>> {
        const { socialAccountIds } = request;
        const _queryParams: Record<string, unknown> = {
            socialAccountIds,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                "v0/posts/counts/by-tab",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Schedulin.CountByTabPostsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Schedulin.BadRequestError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Schedulin.ForbiddenError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new Schedulin.UnprocessableEntityError(
                        _response.error.body as Schedulin.ValidationErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Schedulin.TooManyRequestsError(
                        _response.error.body as Schedulin.RateLimitErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v0/posts/counts/by-tab");
    }

    /**
     * Retrieve a single post by its ID with all relations
     *
     * @param {Schedulin.RetrievePostsRequest} request
     * @param {PostsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.BadRequestError}
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.ForbiddenError}
     * @throws {@link Schedulin.NotFoundError}
     * @throws {@link Schedulin.UnprocessableEntityError}
     * @throws {@link Schedulin.TooManyRequestsError}
     * @throws {@link Schedulin.InternalServerError}
     * @throws {@link errors.SchedulinError}
     * @throws {@link errors.SchedulinTimeoutError}
     *
     * @example
     *     await client.posts.retrieve({
     *         id: "id"
     *     })
     */
    public retrieve(
        request: Schedulin.RetrievePostsRequest,
        requestOptions?: PostsClient.RequestOptions,
    ): core.HttpResponsePromise<Schedulin.PostWithRelations> {
        return core.HttpResponsePromise.fromPromise(this.__retrieve(request, requestOptions));
    }

    private async __retrieve(
        request: Schedulin.RetrievePostsRequest,
        requestOptions?: PostsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Schedulin.PostWithRelations>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                `v0/posts/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Schedulin.PostWithRelations, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Schedulin.BadRequestError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Schedulin.ForbiddenError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Schedulin.NotFoundError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new Schedulin.UnprocessableEntityError(
                        _response.error.body as Schedulin.ValidationErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Schedulin.TooManyRequestsError(
                        _response.error.body as Schedulin.RateLimitErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v0/posts/{id}");
    }

    /**
     * Update an existing draft or scheduled post by its ID. `status` may be DRAFT, SCHEDULED (requires a future `scheduledAt`, either in this request or already on the post), or PROCESSING (publish now). COMPLETED and FAILED are set only by the publisher. A new `scheduledAt` must not be in the past, whatever the status (422). `media` replaces the post's media and accepts the same items as create — a stored or public URL (`{ url }`) or a media library id (`{ id }`), so the `media` array from `GET /v0/posts/{id}` can be sent back as-is. `parts` (X and Mastodon only) replaces the post's thread with the same items create accepts — part media may also be a library `{ id }`, so the `parts` array from `GET /v0/posts/{id}` round-trips — and an empty array removes the thread. On X, parts[0] is the opening tweet: sending `parts` without `caption` sets the caption to parts[0], and changing `caption` or `media` without `parts` updates parts[0] when it matched the old value. Posts that are already publishing, published, or failed can't be edited (409).
     *
     * @param {Schedulin.UpdatePostsRequest} request
     * @param {PostsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.BadRequestError}
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.PaymentRequiredError}
     * @throws {@link Schedulin.ForbiddenError}
     * @throws {@link Schedulin.NotFoundError}
     * @throws {@link Schedulin.ConflictError}
     * @throws {@link Schedulin.UnprocessableEntityError}
     * @throws {@link Schedulin.TooManyRequestsError}
     * @throws {@link Schedulin.InternalServerError}
     * @throws {@link errors.SchedulinError}
     * @throws {@link errors.SchedulinTimeoutError}
     *
     * @example
     *     await client.posts.update({
     *         id: "id"
     *     })
     */
    public update(
        request: Schedulin.UpdatePostsRequest,
        requestOptions?: PostsClient.RequestOptions,
    ): core.HttpResponsePromise<Schedulin.Post> {
        return core.HttpResponsePromise.fromPromise(this.__update(request, requestOptions));
    }

    private async __update(
        request: Schedulin.UpdatePostsRequest,
        requestOptions?: PostsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Schedulin.Post>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                `v0/posts/${core.url.encodePathParam(id)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Schedulin.Post, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Schedulin.BadRequestError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 402:
                    throw new Schedulin.PaymentRequiredError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Schedulin.ForbiddenError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Schedulin.NotFoundError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new Schedulin.ConflictError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new Schedulin.UnprocessableEntityError(
                        _response.error.body as Schedulin.ValidationErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Schedulin.TooManyRequestsError(
                        _response.error.body as Schedulin.RateLimitErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PUT", "/v0/posts/{id}");
    }

    /**
     * Delete a post by its ID
     *
     * @param {Schedulin.DeletePostsRequest} request
     * @param {PostsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.BadRequestError}
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.ForbiddenError}
     * @throws {@link Schedulin.NotFoundError}
     * @throws {@link Schedulin.ConflictError}
     * @throws {@link Schedulin.UnprocessableEntityError}
     * @throws {@link Schedulin.TooManyRequestsError}
     * @throws {@link Schedulin.InternalServerError}
     * @throws {@link errors.SchedulinError}
     * @throws {@link errors.SchedulinTimeoutError}
     *
     * @example
     *     await client.posts.delete({
     *         id: "id"
     *     })
     */
    public delete(
        request: Schedulin.DeletePostsRequest,
        requestOptions?: PostsClient.RequestOptions,
    ): core.HttpResponsePromise<Schedulin.Post> {
        return core.HttpResponsePromise.fromPromise(this.__delete(request, requestOptions));
    }

    private async __delete(
        request: Schedulin.DeletePostsRequest,
        requestOptions?: PostsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Schedulin.Post>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                `v0/posts/${core.url.encodePathParam(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Schedulin.Post, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Schedulin.BadRequestError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Schedulin.ForbiddenError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Schedulin.NotFoundError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new Schedulin.ConflictError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new Schedulin.UnprocessableEntityError(
                        _response.error.body as Schedulin.ValidationErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Schedulin.TooManyRequestsError(
                        _response.error.body as Schedulin.RateLimitErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/v0/posts/{id}");
    }

    /**
     * Retrieve the latest analytics snapshot for a post
     *
     * @param {Schedulin.AnalyticsSummaryPostsRequest} request
     * @param {PostsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.BadRequestError}
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.ForbiddenError}
     * @throws {@link Schedulin.NotFoundError}
     * @throws {@link Schedulin.UnprocessableEntityError}
     * @throws {@link Schedulin.TooManyRequestsError}
     * @throws {@link Schedulin.InternalServerError}
     * @throws {@link errors.SchedulinError}
     * @throws {@link errors.SchedulinTimeoutError}
     *
     * @example
     *     await client.posts.analyticsSummary({
     *         id: "id"
     *     })
     */
    public analyticsSummary(
        request: Schedulin.AnalyticsSummaryPostsRequest,
        requestOptions?: PostsClient.RequestOptions,
    ): core.HttpResponsePromise<Schedulin.AnalyticsSummaryPostsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__analyticsSummary(request, requestOptions));
    }

    private async __analyticsSummary(
        request: Schedulin.AnalyticsSummaryPostsRequest,
        requestOptions?: PostsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Schedulin.AnalyticsSummaryPostsResponse>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                `v0/posts/${core.url.encodePathParam(id)}/analytics/summary`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Schedulin.AnalyticsSummaryPostsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Schedulin.BadRequestError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Schedulin.ForbiddenError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Schedulin.NotFoundError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new Schedulin.UnprocessableEntityError(
                        _response.error.body as Schedulin.ValidationErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Schedulin.TooManyRequestsError(
                        _response.error.body as Schedulin.RateLimitErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v0/posts/{id}/analytics/summary",
        );
    }

    /**
     * Retrieve time series analytics metrics for a post
     *
     * @param {Schedulin.AnalyticsSeriesPostsRequest} request
     * @param {PostsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.BadRequestError}
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.ForbiddenError}
     * @throws {@link Schedulin.NotFoundError}
     * @throws {@link Schedulin.UnprocessableEntityError}
     * @throws {@link Schedulin.TooManyRequestsError}
     * @throws {@link Schedulin.InternalServerError}
     * @throws {@link errors.SchedulinError}
     * @throws {@link errors.SchedulinTimeoutError}
     *
     * @example
     *     await client.posts.analyticsSeries({
     *         id: "id"
     *     })
     */
    public analyticsSeries(
        request: Schedulin.AnalyticsSeriesPostsRequest,
        requestOptions?: PostsClient.RequestOptions,
    ): core.HttpResponsePromise<Schedulin.AnalyticsSeriesPostsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__analyticsSeries(request, requestOptions));
    }

    private async __analyticsSeries(
        request: Schedulin.AnalyticsSeriesPostsRequest,
        requestOptions?: PostsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Schedulin.AnalyticsSeriesPostsResponse>> {
        const { id, limit } = request;
        const _queryParams: Record<string, unknown> = {
            limit,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                `v0/posts/${core.url.encodePathParam(id)}/analytics/series`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Schedulin.AnalyticsSeriesPostsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Schedulin.BadRequestError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Schedulin.ForbiddenError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Schedulin.NotFoundError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new Schedulin.UnprocessableEntityError(
                        _response.error.body as Schedulin.ValidationErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Schedulin.TooManyRequestsError(
                        _response.error.body as Schedulin.RateLimitErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v0/posts/{id}/analytics/series",
        );
    }

    /**
     * Publish a draft post to connected social media accounts
     *
     * @param {Schedulin.PublishDraftPostsRequest} request
     * @param {PostsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.BadRequestError}
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.PaymentRequiredError}
     * @throws {@link Schedulin.ForbiddenError}
     * @throws {@link Schedulin.NotFoundError}
     * @throws {@link Schedulin.ConflictError}
     * @throws {@link Schedulin.UnprocessableEntityError}
     * @throws {@link Schedulin.TooManyRequestsError}
     * @throws {@link Schedulin.InternalServerError}
     * @throws {@link errors.SchedulinError}
     * @throws {@link errors.SchedulinTimeoutError}
     *
     * @example
     *     await client.posts.publishDraft({
     *         id: "id"
     *     })
     */
    public publishDraft(
        request: Schedulin.PublishDraftPostsRequest,
        requestOptions?: PostsClient.RequestOptions,
    ): core.HttpResponsePromise<Schedulin.Post> {
        return core.HttpResponsePromise.fromPromise(this.__publishDraft(request, requestOptions));
    }

    private async __publishDraft(
        request: Schedulin.PublishDraftPostsRequest,
        requestOptions?: PostsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Schedulin.Post>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                `v0/posts/${core.url.encodePathParam(id)}/publish`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Schedulin.Post, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Schedulin.BadRequestError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 402:
                    throw new Schedulin.PaymentRequiredError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Schedulin.ForbiddenError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Schedulin.NotFoundError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new Schedulin.ConflictError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new Schedulin.UnprocessableEntityError(
                        _response.error.body as Schedulin.ValidationErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Schedulin.TooManyRequestsError(
                        _response.error.body as Schedulin.RateLimitErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v0/posts/{id}/publish");
    }

    /**
     * Replace all tags on a post. No status restrictions apply.
     *
     * @param {Schedulin.UpdateTagsPostsRequest} request
     * @param {PostsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.BadRequestError}
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.ForbiddenError}
     * @throws {@link Schedulin.NotFoundError}
     * @throws {@link Schedulin.ConflictError}
     * @throws {@link Schedulin.UnprocessableEntityError}
     * @throws {@link Schedulin.TooManyRequestsError}
     * @throws {@link Schedulin.InternalServerError}
     * @throws {@link errors.SchedulinError}
     * @throws {@link errors.SchedulinTimeoutError}
     *
     * @example
     *     await client.posts.updateTags({
     *         id: "id",
     *         tagIds: ["tagIds"]
     *     })
     */
    public updateTags(
        request: Schedulin.UpdateTagsPostsRequest,
        requestOptions?: PostsClient.RequestOptions,
    ): core.HttpResponsePromise<Schedulin.Post> {
        return core.HttpResponsePromise.fromPromise(this.__updateTags(request, requestOptions));
    }

    private async __updateTags(
        request: Schedulin.UpdateTagsPostsRequest,
        requestOptions?: PostsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Schedulin.Post>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                `v0/posts/${core.url.encodePathParam(id)}/tags`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Schedulin.Post, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Schedulin.BadRequestError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Schedulin.ForbiddenError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Schedulin.NotFoundError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new Schedulin.ConflictError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new Schedulin.UnprocessableEntityError(
                        _response.error.body as Schedulin.ValidationErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Schedulin.TooManyRequestsError(
                        _response.error.body as Schedulin.RateLimitErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PUT", "/v0/posts/{id}/tags");
    }
}
