// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface UpdateTagsRequest {
    id: string;
    name?: string;
    color?: string;
}
