// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id",
 *         name: "name",
 *         color: "color"
 *     }
 */
export interface UpdateTagsRequest {
    id: string;
    name: string;
    color: string;
}
