// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         contentType: "contentType",
 *         key: "key"
 *     }
 */
export interface CreatePresignedPost {
    contentType: string;
    key: string;
    size?: number;
    intent?: CreatePresignedPost.Intent;
}

export namespace CreatePresignedPost {
    export const Intent = {
        Post: "post",
        ClipSource: "clip-source",
        PublicAsset: "public-asset",
    } as const;
    export type Intent = (typeof Intent)[keyof typeof Intent];
}
