// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         url: "url"
 *     }
 */
export interface CreateFromUrlMediaRequest {
    url: string;
    name?: string;
    alt?: string | null;
    contentType?: string;
}
