// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         contentType: "contentType",
 *         key: "key"
 *     }
 */
export interface CreatePresignedPost {
    contentType: string;
    key: string;
    size?: number;
}
