// This file was auto-generated by Fern from our API Definition.

import type * as Schedulin from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListMediaRequest {
    cursor?: Schedulin.ListMediaRequestCursor | null;
    limit?: number;
    q?: string;
    type?: Schedulin.ListMediaRequestType;
    tagIds?: string | string[];
    tagMode?: Schedulin.ListMediaRequestTagMode;
}
