// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         key: "key"
 *     }
 */
export interface MediaRegister {
    /** The `key` returned by POST /v0/media/presign, after the bytes were PUT to its `url`. The stored media URL for that key is also accepted. */
    key: string;
    name?: string;
    alt?: string | null;
}
