// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         mediaId: "mediaId",
 *         tagIds: ["tagIds"]
 *     }
 */
export interface SetTagsMediaRequest {
    mediaId: string;
    tagIds: string[];
}
