// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id",
 *         url: "url"
 *     }
 */
export interface UpdateMediaRequest {
    id: string;
    url: string;
    mimeType?: string;
    width?: number;
    height?: number;
    size?: number;
    duration?: number;
}
