// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         file: "file"
 *     }
 */
export interface UploadMediaRequest {
    file: string;
    name?: string;
    alt?: string;
    contentType?: string;
}
