// This file was auto-generated by Fern from our API Definition.

import type * as Schedulin from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListPostsRequest {
    cursor?: Schedulin.ListPostsRequestCursor | null;
    page?: number;
    status?: Schedulin.ListPostsRequestStatus;
    scheduledAt?: Schedulin.ListPostsRequestScheduledAt;
    tagIds?: string | string[];
    tagMode?: Schedulin.ListPostsRequestTagMode;
    socialAccountIds?: string | string[];
    limit?: number;
}
