// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         caption: "caption",
 *         socialAccountId: "socialAccountId",
 *         media: [{
 *                 url: "url"
 *             }]
 *     }
 */
export interface PostCreate {
    caption: string;
    scheduledAt?: string | null;
    socialAccountId: string;
    media: PostCreate.Media.Item[];
    thumbnail?: PostCreate.Thumbnail;
    platformConfiguration?: Record<string, unknown>;
    tagIds?: string[];
    action?: PostCreate.Action;
    parts?: PostCreate.Parts.Item[];
}

export namespace PostCreate {
    export type Media = Media.Item[];

    export namespace Media {
        export interface Item {
            url: string;
            thumbnail_url?: (string | null) | undefined;
            thumbnail_timestamp_ms?: (number | null) | undefined;
            tags?: Item.Tags.Item[] | undefined;
            alt?: (string | null) | undefined;
            skip_processing?: boolean | undefined;
            name?: string | undefined;
            mimeType?: string | undefined;
            width?: number | undefined;
            height?: number | undefined;
            size?: number | undefined;
            duration?: number | undefined;
        }

        export namespace Item {
            export type Tags = Tags.Item[];

            export namespace Tags {
                export interface Item {
                    id: string;
                    type: Item.Type;
                    platform: Item.Platform;
                    x?: number | undefined;
                    y?: number | undefined;
                }

                export namespace Item {
                    export const Type = {
                        User: "user",
                        Business: "business",
                    } as const;
                    export type Type = (typeof Type)[keyof typeof Type];
                    export const Platform = {
                        Bluesky: "bluesky",
                        Facebook: "facebook",
                        Instagram: "instagram",
                        Linkedin: "linkedin",
                        Pinterest: "pinterest",
                        Threads: "threads",
                        Tiktok: "tiktok",
                        Twitter: "twitter",
                        Youtube: "youtube",
                    } as const;
                    export type Platform = (typeof Platform)[keyof typeof Platform];
                }
            }
        }
    }

    export interface Thumbnail {
        url: string;
        thumbnail_url?: (string | null) | undefined;
        thumbnail_timestamp_ms?: (number | null) | undefined;
        tags?: Thumbnail.Tags.Item[] | undefined;
        alt?: (string | null) | undefined;
        skip_processing?: boolean | undefined;
        name?: string | undefined;
        mimeType?: string | undefined;
        width?: number | undefined;
        height?: number | undefined;
        size?: number | undefined;
        duration?: number | undefined;
    }

    export namespace Thumbnail {
        export type Tags = Tags.Item[];

        export namespace Tags {
            export interface Item {
                id: string;
                type: Item.Type;
                platform: Item.Platform;
                x?: number | undefined;
                y?: number | undefined;
            }

            export namespace Item {
                export const Type = {
                    User: "user",
                    Business: "business",
                } as const;
                export type Type = (typeof Type)[keyof typeof Type];
                export const Platform = {
                    Bluesky: "bluesky",
                    Facebook: "facebook",
                    Instagram: "instagram",
                    Linkedin: "linkedin",
                    Pinterest: "pinterest",
                    Threads: "threads",
                    Tiktok: "tiktok",
                    Twitter: "twitter",
                    Youtube: "youtube",
                } as const;
                export type Platform = (typeof Platform)[keyof typeof Platform];
            }
        }
    }

    export const Action = {
        Schedule: "schedule",
        Queue: "queue",
        Draft: "draft",
    } as const;
    export type Action = (typeof Action)[keyof typeof Action];
    export type Parts = Parts.Item[];

    export namespace Parts {
        export interface Item {
            caption: string;
            media?: Item.Media.Item[] | undefined;
        }

        export namespace Item {
            export type Media = Media.Item[];

            export namespace Media {
                export interface Item {
                    url: string;
                    thumbnail_url?: (string | null) | undefined;
                    thumbnail_timestamp_ms?: (number | null) | undefined;
                    tags?: Item.Tags.Item[] | undefined;
                    alt?: (string | null) | undefined;
                    skip_processing?: boolean | undefined;
                    name?: string | undefined;
                    mimeType?: string | undefined;
                    width?: number | undefined;
                    height?: number | undefined;
                    size?: number | undefined;
                    duration?: number | undefined;
                }

                export namespace Item {
                    export type Tags = Tags.Item[];

                    export namespace Tags {
                        export interface Item {
                            id: string;
                            type: Item.Type;
                            platform: Item.Platform;
                            x?: number | undefined;
                            y?: number | undefined;
                        }

                        export namespace Item {
                            export const Type = {
                                User: "user",
                                Business: "business",
                            } as const;
                            export type Type = (typeof Type)[keyof typeof Type];
                            export const Platform = {
                                Bluesky: "bluesky",
                                Facebook: "facebook",
                                Instagram: "instagram",
                                Linkedin: "linkedin",
                                Pinterest: "pinterest",
                                Threads: "threads",
                                Tiktok: "tiktok",
                                Twitter: "twitter",
                                Youtube: "youtube",
                            } as const;
                            export type Platform = (typeof Platform)[keyof typeof Platform];
                        }
                    }
                }
            }
        }
    }
}
