// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface UpdatePostsRequest {
    id: string;
    caption?: string;
    scheduledAt?: string | null;
    media?: UpdatePostsRequest.Media.Item[];
    platformConfiguration?: Record<string, unknown>;
    status?: UpdatePostsRequest.Status;
    tagIds?: string[];
}

export namespace UpdatePostsRequest {
    export type Media = Media.Item[];

    export namespace Media {
        export interface Item {
            id: string;
            name: string;
            url: string;
            mimeType: string;
            bucket?: string | undefined;
            key: string;
        }
    }

    export const Status = {
        Draft: "DRAFT",
        Scheduled: "SCHEDULED",
        Processing: "PROCESSING",
        Completed: "COMPLETED",
        Failed: "FAILED",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
