// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id",
 *         tagIds: ["tagIds"]
 *     }
 */
export interface UpdateTagsPostsRequest {
    id: string;
    tagIds: string[];
}
