// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface UpdatePostsRequest {
    id: string;
    caption?: string;
    scheduledAt?: string | null;
    media?: UpdatePostsRequest.Media.Item[];
    platformConfiguration?: Record<string, unknown>;
    status?: UpdatePostsRequest.Status;
    tagIds?: string[];
}

export namespace UpdatePostsRequest {
    export type Media = Media.Item[];

    export namespace Media {
        export interface Item {
            id?: string | undefined;
            url?: string | undefined;
            name?: string | undefined;
            mimeType?: string | undefined;
            width?: (number | null) | undefined;
            height?: (number | null) | undefined;
            size?: (number | null) | undefined;
            duration?: (number | null) | undefined;
            alt?: (string | null) | undefined;
            bucket?: string | undefined;
            key?: string | undefined;
        }
    }

    export const Status = {
        Draft: "DRAFT",
        Scheduled: "SCHEDULED",
        Processing: "PROCESSING",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
