// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface UpdatePostsRequest {
    id: string;
    caption?: string;
    scheduledAt?: string | null;
    media?: UpdatePostsRequest.Media.Item[];
    platformConfiguration?: Record<string, unknown>;
    status?: UpdatePostsRequest.Status;
    tagIds?: string[];
    parts?: UpdatePostsRequest.Parts.Item[];
}

export namespace UpdatePostsRequest {
    export type Media = Media.Item[];

    export namespace Media {
        export interface Item {
            id?: string | undefined;
            url?: string | undefined;
            name?: string | undefined;
            mimeType?: string | undefined;
            width?: (number | null) | undefined;
            height?: (number | null) | undefined;
            size?: (number | null) | undefined;
            duration?: (number | null) | undefined;
            alt?: (string | null) | undefined;
            tags?: (Item.Tags.Item[] | null) | undefined;
            bucket?: string | undefined;
            key?: string | undefined;
        }

        export namespace Item {
            export type Tags = Tags.Item[];

            export namespace Tags {
                export interface Item {
                    id: string;
                    type: Item.Type;
                    platform: Item.Platform;
                    x?: number | undefined;
                    y?: number | undefined;
                }

                export namespace Item {
                    export const Type = {
                        User: "user",
                        Business: "business",
                    } as const;
                    export type Type = (typeof Type)[keyof typeof Type];
                    export const Platform = {
                        Bluesky: "bluesky",
                        Facebook: "facebook",
                        GoogleBusinessProfile: "google_business_profile",
                        Instagram: "instagram",
                        Linkedin: "linkedin",
                        Pinterest: "pinterest",
                        Reddit: "reddit",
                        Snapchat: "snapchat",
                        Threads: "threads",
                        Tiktok: "tiktok",
                        Twitter: "twitter",
                        Youtube: "youtube",
                        Mastodon: "mastodon",
                        Telegram: "telegram",
                        Devto: "devto",
                        Hashnode: "hashnode",
                        Medium: "medium",
                        Wordpress: "wordpress",
                        Lemmy: "lemmy",
                        Nostr: "nostr",
                        Discord: "discord",
                        Dribbble: "dribbble",
                        Farcaster: "farcaster",
                        Kick: "kick",
                        Listmonk: "listmonk",
                        Mewe: "mewe",
                        Moltbook: "moltbook",
                        Skool: "skool",
                        Slack: "slack",
                        Twitch: "twitch",
                        Vk: "vk",
                        Whop: "whop",
                    } as const;
                    export type Platform = (typeof Platform)[keyof typeof Platform];
                }
            }
        }
    }

    export const Status = {
        Draft: "DRAFT",
        Scheduled: "SCHEDULED",
        Processing: "PROCESSING",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
    export type Parts = Parts.Item[];

    export namespace Parts {
        export interface Item {
            caption: string;
            media?: Item.Media.Item[] | undefined;
        }

        export namespace Item {
            export type Media = Media.Item[];

            export namespace Media {
                export interface Item {
                    id?: string | undefined;
                    url?: string | undefined;
                    name?: string | undefined;
                    mimeType?: string | undefined;
                    width?: (number | null) | undefined;
                    height?: (number | null) | undefined;
                    size?: (number | null) | undefined;
                    duration?: (number | null) | undefined;
                    alt?: (string | null) | undefined;
                    tags?: (Item.Tags.Item[] | null) | undefined;
                    bucket?: string | undefined;
                    key?: string | undefined;
                }

                export namespace Item {
                    export type Tags = Tags.Item[];

                    export namespace Tags {
                        export interface Item {
                            id: string;
                            type: Item.Type;
                            platform: Item.Platform;
                            x?: number | undefined;
                            y?: number | undefined;
                        }

                        export namespace Item {
                            export const Type = {
                                User: "user",
                                Business: "business",
                            } as const;
                            export type Type = (typeof Type)[keyof typeof Type];
                            export const Platform = {
                                Bluesky: "bluesky",
                                Facebook: "facebook",
                                GoogleBusinessProfile: "google_business_profile",
                                Instagram: "instagram",
                                Linkedin: "linkedin",
                                Pinterest: "pinterest",
                                Reddit: "reddit",
                                Snapchat: "snapchat",
                                Threads: "threads",
                                Tiktok: "tiktok",
                                Twitter: "twitter",
                                Youtube: "youtube",
                                Mastodon: "mastodon",
                                Telegram: "telegram",
                                Devto: "devto",
                                Hashnode: "hashnode",
                                Medium: "medium",
                                Wordpress: "wordpress",
                                Lemmy: "lemmy",
                                Nostr: "nostr",
                                Discord: "discord",
                                Dribbble: "dribbble",
                                Farcaster: "farcaster",
                                Kick: "kick",
                                Listmonk: "listmonk",
                                Mewe: "mewe",
                                Moltbook: "moltbook",
                                Skool: "skool",
                                Slack: "slack",
                                Twitch: "twitch",
                                Vk: "vk",
                                Whop: "whop",
                            } as const;
                            export type Platform = (typeof Platform)[keyof typeof Platform];
                        }
                    }
                }
            }
        }
    }
}
