// This file was auto-generated by Fern from our API Definition.

export interface ListPlatformsResponse {
    data: ListPlatformsResponse.Data.Item[];
}

export namespace ListPlatformsResponse {
    export type Data = Data.Item[];

    export namespace Data {
        export interface Item {
            platform: string;
            name: string;
            comingSoon?: boolean | undefined;
            captionMaxLength?: number | undefined;
            mediaRules?: Item.MediaRules | undefined;
            platformConfiguration: Item.PlatformConfiguration;
            helperEndpoints?: Item.HelperEndpoints.Item[] | undefined;
        }

        export namespace Item {
            export interface MediaRules {
                min?: number | undefined;
                max: number;
                allowedTypes?: MediaRules.AllowedTypes.Item[] | undefined;
                allowedDimensions?: MediaRules.AllowedDimensions.Item[] | undefined;
            }

            export namespace MediaRules {
                export type AllowedTypes = AllowedTypes.Item[];

                export namespace AllowedTypes {
                    export const Item = {
                        Image: "IMAGE",
                        Video: "VIDEO",
                        Gif: "GIF",
                    } as const;
                    export type Item = (typeof Item)[keyof typeof Item];
                }

                export type AllowedDimensions = AllowedDimensions.Item[];

                export namespace AllowedDimensions {
                    export interface Item {
                        width: number;
                        height: number;
                    }
                }
            }

            export interface PlatformConfiguration {
                required: boolean;
                validated: boolean;
                schema?: Record<string, unknown> | undefined;
            }

            export type HelperEndpoints = HelperEndpoints.Item[];

            export namespace HelperEndpoints {
                export interface Item {
                    method: string;
                    path: string;
                    description: string;
                }
            }
        }
    }
}
