// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Schedulin from "../../../index.js";

export declare namespace SocialAccountsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class SocialAccountsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<SocialAccountsClient.Options>;

    constructor(options: SocialAccountsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Retrieve all connected social media accounts for the authenticated user
     *
     * @param {SocialAccountsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.BadRequestError}
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.ForbiddenError}
     * @throws {@link Schedulin.UnprocessableEntityError}
     * @throws {@link Schedulin.TooManyRequestsError}
     * @throws {@link Schedulin.InternalServerError}
     * @throws {@link errors.SchedulinError}
     * @throws {@link errors.SchedulinTimeoutError}
     *
     * @example
     *     await client.socialAccounts.list()
     */
    public list(
        requestOptions?: SocialAccountsClient.RequestOptions,
    ): core.HttpResponsePromise<Schedulin.ListSocialAccountsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__list(requestOptions));
    }

    private async __list(
        requestOptions?: SocialAccountsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Schedulin.ListSocialAccountsResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                "v0/social-accounts",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Schedulin.ListSocialAccountsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Schedulin.BadRequestError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Schedulin.ForbiddenError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new Schedulin.UnprocessableEntityError(
                        _response.error.body as Schedulin.ValidationErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Schedulin.TooManyRequestsError(
                        _response.error.body as Schedulin.RateLimitErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v0/social-accounts");
    }

    /**
     * List companies available to a connected Whop account. Select one before requesting its forum experiences.
     *
     * @param {Schedulin.ListWhopCompaniesSocialAccountsRequest} request
     * @param {SocialAccountsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.BadRequestError}
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.ForbiddenError}
     * @throws {@link Schedulin.NotFoundError}
     * @throws {@link Schedulin.UnprocessableEntityError}
     * @throws {@link Schedulin.TooManyRequestsError}
     * @throws {@link Schedulin.InternalServerError}
     * @throws {@link errors.SchedulinError}
     * @throws {@link errors.SchedulinTimeoutError}
     *
     * @example
     *     await client.socialAccounts.listWhopCompanies({
     *         id: "id"
     *     })
     */
    public listWhopCompanies(
        request: Schedulin.ListWhopCompaniesSocialAccountsRequest,
        requestOptions?: SocialAccountsClient.RequestOptions,
    ): core.HttpResponsePromise<Schedulin.ListWhopCompaniesSocialAccountsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listWhopCompanies(request, requestOptions));
    }

    private async __listWhopCompanies(
        request: Schedulin.ListWhopCompaniesSocialAccountsRequest,
        requestOptions?: SocialAccountsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Schedulin.ListWhopCompaniesSocialAccountsResponse>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                `v0/social-accounts/${core.url.encodePathParam(id)}/whop-companies`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Schedulin.ListWhopCompaniesSocialAccountsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Schedulin.BadRequestError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Schedulin.ForbiddenError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Schedulin.NotFoundError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new Schedulin.UnprocessableEntityError(
                        _response.error.body as Schedulin.ValidationErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Schedulin.TooManyRequestsError(
                        _response.error.body as Schedulin.RateLimitErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v0/social-accounts/{id}/whop-companies",
        );
    }

    /**
     * List forum experiences for a Whop company. Use an item id as platformConfiguration.experience.
     *
     * @param {Schedulin.ListWhopForumsSocialAccountsRequest} request
     * @param {SocialAccountsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.BadRequestError}
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.ForbiddenError}
     * @throws {@link Schedulin.NotFoundError}
     * @throws {@link Schedulin.UnprocessableEntityError}
     * @throws {@link Schedulin.TooManyRequestsError}
     * @throws {@link Schedulin.InternalServerError}
     * @throws {@link errors.SchedulinError}
     * @throws {@link errors.SchedulinTimeoutError}
     *
     * @example
     *     await client.socialAccounts.listWhopForums({
     *         id: "id",
     *         companyId: "companyId"
     *     })
     */
    public listWhopForums(
        request: Schedulin.ListWhopForumsSocialAccountsRequest,
        requestOptions?: SocialAccountsClient.RequestOptions,
    ): core.HttpResponsePromise<Schedulin.ListWhopForumsSocialAccountsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listWhopForums(request, requestOptions));
    }

    private async __listWhopForums(
        request: Schedulin.ListWhopForumsSocialAccountsRequest,
        requestOptions?: SocialAccountsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Schedulin.ListWhopForumsSocialAccountsResponse>> {
        const { id, companyId } = request;
        const _queryParams: Record<string, unknown> = {
            companyId,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                `v0/social-accounts/${core.url.encodePathParam(id)}/whop-forums`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Schedulin.ListWhopForumsSocialAccountsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Schedulin.BadRequestError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Schedulin.ForbiddenError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Schedulin.NotFoundError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new Schedulin.UnprocessableEntityError(
                        _response.error.body as Schedulin.ValidationErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Schedulin.TooManyRequestsError(
                        _response.error.body as Schedulin.RateLimitErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v0/social-accounts/{id}/whop-forums",
        );
    }

    /**
     * List the text and announcement channels the Schedulin bot can post into for a connected Discord server — only channels where the bot's effective permissions (its roles plus the channel's permission overwrites) include View Channel and Send Messages; channels it can't post in are omitted. Use an item id as `platformConfiguration.channel` when creating a Discord post.
     *
     * @param {Schedulin.ListDiscordChannelsSocialAccountsRequest} request
     * @param {SocialAccountsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.BadRequestError}
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.ForbiddenError}
     * @throws {@link Schedulin.NotFoundError}
     * @throws {@link Schedulin.UnprocessableEntityError}
     * @throws {@link Schedulin.TooManyRequestsError}
     * @throws {@link Schedulin.InternalServerError}
     * @throws {@link errors.SchedulinError}
     * @throws {@link errors.SchedulinTimeoutError}
     *
     * @example
     *     await client.socialAccounts.listDiscordChannels({
     *         id: "id"
     *     })
     */
    public listDiscordChannels(
        request: Schedulin.ListDiscordChannelsSocialAccountsRequest,
        requestOptions?: SocialAccountsClient.RequestOptions,
    ): core.HttpResponsePromise<Schedulin.ListDiscordChannelsSocialAccountsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listDiscordChannels(request, requestOptions));
    }

    private async __listDiscordChannels(
        request: Schedulin.ListDiscordChannelsSocialAccountsRequest,
        requestOptions?: SocialAccountsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Schedulin.ListDiscordChannelsSocialAccountsResponse>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                `v0/social-accounts/${core.url.encodePathParam(id)}/discord-channels`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Schedulin.ListDiscordChannelsSocialAccountsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Schedulin.BadRequestError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Schedulin.ForbiddenError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Schedulin.NotFoundError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new Schedulin.UnprocessableEntityError(
                        _response.error.body as Schedulin.ValidationErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Schedulin.TooManyRequestsError(
                        _response.error.body as Schedulin.RateLimitErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v0/social-accounts/{id}/discord-channels",
        );
    }

    /**
     * List the channels in a connected Slack workspace that the Schedulin bot can post into (public channels, plus private channels it was invited to). Use an item id as `platformConfiguration.channel` when creating a Slack post.
     *
     * @param {Schedulin.ListSlackChannelsSocialAccountsRequest} request
     * @param {SocialAccountsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.BadRequestError}
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.ForbiddenError}
     * @throws {@link Schedulin.NotFoundError}
     * @throws {@link Schedulin.UnprocessableEntityError}
     * @throws {@link Schedulin.TooManyRequestsError}
     * @throws {@link Schedulin.InternalServerError}
     * @throws {@link errors.SchedulinError}
     * @throws {@link errors.SchedulinTimeoutError}
     *
     * @example
     *     await client.socialAccounts.listSlackChannels({
     *         id: "id"
     *     })
     */
    public listSlackChannels(
        request: Schedulin.ListSlackChannelsSocialAccountsRequest,
        requestOptions?: SocialAccountsClient.RequestOptions,
    ): core.HttpResponsePromise<Schedulin.ListSlackChannelsSocialAccountsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listSlackChannels(request, requestOptions));
    }

    private async __listSlackChannels(
        request: Schedulin.ListSlackChannelsSocialAccountsRequest,
        requestOptions?: SocialAccountsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Schedulin.ListSlackChannelsSocialAccountsResponse>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                `v0/social-accounts/${core.url.encodePathParam(id)}/slack-channels`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Schedulin.ListSlackChannelsSocialAccountsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Schedulin.BadRequestError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Schedulin.ForbiddenError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Schedulin.NotFoundError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new Schedulin.UnprocessableEntityError(
                        _response.error.body as Schedulin.ValidationErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Schedulin.TooManyRequestsError(
                        _response.error.body as Schedulin.RateLimitErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v0/social-accounts/{id}/slack-channels",
        );
    }

    /**
     * Update social media account settings and information
     *
     * @param {Schedulin.UpdateSocialAccountsRequest} request
     * @param {SocialAccountsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.BadRequestError}
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.ForbiddenError}
     * @throws {@link Schedulin.NotFoundError}
     * @throws {@link Schedulin.ConflictError}
     * @throws {@link Schedulin.UnprocessableEntityError}
     * @throws {@link Schedulin.TooManyRequestsError}
     * @throws {@link Schedulin.InternalServerError}
     * @throws {@link errors.SchedulinError}
     * @throws {@link errors.SchedulinTimeoutError}
     *
     * @example
     *     await client.socialAccounts.update({
     *         id: "id"
     *     })
     */
    public update(
        request: Schedulin.UpdateSocialAccountsRequest,
        requestOptions?: SocialAccountsClient.RequestOptions,
    ): core.HttpResponsePromise<Schedulin.UpdateSocialAccountsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__update(request, requestOptions));
    }

    private async __update(
        request: Schedulin.UpdateSocialAccountsRequest,
        requestOptions?: SocialAccountsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Schedulin.UpdateSocialAccountsResponse>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                `v0/social-accounts/${core.url.encodePathParam(id)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Schedulin.UpdateSocialAccountsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Schedulin.BadRequestError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Schedulin.ForbiddenError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Schedulin.NotFoundError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new Schedulin.ConflictError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new Schedulin.UnprocessableEntityError(
                        _response.error.body as Schedulin.ValidationErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Schedulin.TooManyRequestsError(
                        _response.error.body as Schedulin.RateLimitErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PUT", "/v0/social-accounts/{id}");
    }

    /**
     * Disconnect a social account. By default this is a soft disconnect: the stored credentials are wiped, the account stops counting toward your plan's account limit, and it stays in `GET /v0/social-accounts` with `status: "disconnected"` and `disconnectedReason: "TOKEN_REVOKED"` until it is reconnected from the dashboard. All of its posts, analytics, and history are kept; scheduled posts that come due while it is disconnected fail with a "reconnect" error instead of publishing. Pass `permanent=true` to delete the account instead — this **permanently deletes every post** (scheduled, draft, and published history) of the account and cannot be undone.
     *
     * @param {Schedulin.DeleteSocialAccountsRequest} request
     * @param {SocialAccountsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.BadRequestError}
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.ForbiddenError}
     * @throws {@link Schedulin.NotFoundError}
     * @throws {@link Schedulin.ConflictError}
     * @throws {@link Schedulin.UnprocessableEntityError}
     * @throws {@link Schedulin.TooManyRequestsError}
     * @throws {@link Schedulin.InternalServerError}
     * @throws {@link errors.SchedulinError}
     * @throws {@link errors.SchedulinTimeoutError}
     *
     * @example
     *     await client.socialAccounts.delete({
     *         id: "id"
     *     })
     */
    public delete(
        request: Schedulin.DeleteSocialAccountsRequest,
        requestOptions?: SocialAccountsClient.RequestOptions,
    ): core.HttpResponsePromise<Schedulin.DeleteSocialAccountsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__delete(request, requestOptions));
    }

    private async __delete(
        request: Schedulin.DeleteSocialAccountsRequest,
        requestOptions?: SocialAccountsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Schedulin.DeleteSocialAccountsResponse>> {
        const { id, permanent, ..._body } = request;
        const _queryParams: Record<string, unknown> = {
            permanent,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                `v0/social-accounts/${core.url.encodePathParam(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Schedulin.DeleteSocialAccountsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Schedulin.BadRequestError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Schedulin.ForbiddenError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Schedulin.NotFoundError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new Schedulin.ConflictError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new Schedulin.UnprocessableEntityError(
                        _response.error.body as Schedulin.ValidationErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Schedulin.TooManyRequestsError(
                        _response.error.body as Schedulin.RateLimitErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/v0/social-accounts/{id}");
    }

    /**
     * Set the IANA timezone (e.g. 'America/Los_Angeles') used to interpret queue times for this account. Unknown names and UTC-offset strings (e.g. '+05:00') are rejected with 422.
     *
     * @param {Schedulin.UpdateTimezoneSocialAccountsRequest} request
     * @param {SocialAccountsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.BadRequestError}
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.ForbiddenError}
     * @throws {@link Schedulin.NotFoundError}
     * @throws {@link Schedulin.ConflictError}
     * @throws {@link Schedulin.UnprocessableEntityError}
     * @throws {@link Schedulin.TooManyRequestsError}
     * @throws {@link Schedulin.InternalServerError}
     * @throws {@link errors.SchedulinError}
     * @throws {@link errors.SchedulinTimeoutError}
     *
     * @example
     *     await client.socialAccounts.updateTimezone({
     *         id: "id",
     *         timezone: "timezone"
     *     })
     */
    public updateTimezone(
        request: Schedulin.UpdateTimezoneSocialAccountsRequest,
        requestOptions?: SocialAccountsClient.RequestOptions,
    ): core.HttpResponsePromise<Schedulin.UpdateTimezoneSocialAccountsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updateTimezone(request, requestOptions));
    }

    private async __updateTimezone(
        request: Schedulin.UpdateTimezoneSocialAccountsRequest,
        requestOptions?: SocialAccountsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Schedulin.UpdateTimezoneSocialAccountsResponse>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                `v0/social-accounts/${core.url.encodePathParam(id)}/timezone`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Schedulin.UpdateTimezoneSocialAccountsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Schedulin.BadRequestError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Schedulin.ForbiddenError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Schedulin.NotFoundError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 409:
                    throw new Schedulin.ConflictError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new Schedulin.UnprocessableEntityError(
                        _response.error.body as Schedulin.ValidationErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Schedulin.TooManyRequestsError(
                        _response.error.body as Schedulin.RateLimitErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/v0/social-accounts/{id}/timezone",
        );
    }

    /**
     * Return the next available queue slot times (UTC) for a social account, computed from its queue schedule, per-slot capacity, and timezone. Empty when the account has no queue times configured. Use a slot as `scheduledAt`, or pass `action: "queue"` when creating a post to take the next slot automatically.
     *
     * @param {Schedulin.NextSlotsSocialAccountsRequest} request
     * @param {SocialAccountsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.BadRequestError}
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.ForbiddenError}
     * @throws {@link Schedulin.NotFoundError}
     * @throws {@link Schedulin.UnprocessableEntityError}
     * @throws {@link Schedulin.TooManyRequestsError}
     * @throws {@link Schedulin.InternalServerError}
     * @throws {@link errors.SchedulinError}
     * @throws {@link errors.SchedulinTimeoutError}
     *
     * @example
     *     await client.socialAccounts.nextSlots({
     *         id: "id"
     *     })
     */
    public nextSlots(
        request: Schedulin.NextSlotsSocialAccountsRequest,
        requestOptions?: SocialAccountsClient.RequestOptions,
    ): core.HttpResponsePromise<Schedulin.NextSlotsSocialAccountsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__nextSlots(request, requestOptions));
    }

    private async __nextSlots(
        request: Schedulin.NextSlotsSocialAccountsRequest,
        requestOptions?: SocialAccountsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Schedulin.NextSlotsSocialAccountsResponse>> {
        const { id, limit, after } = request;
        const _queryParams: Record<string, unknown> = {
            limit,
            after,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                `v0/social-accounts/${core.url.encodePathParam(id)}/next-slots`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Schedulin.NextSlotsSocialAccountsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Schedulin.BadRequestError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Schedulin.ForbiddenError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Schedulin.NotFoundError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new Schedulin.UnprocessableEntityError(
                        _response.error.body as Schedulin.ValidationErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Schedulin.TooManyRequestsError(
                        _response.error.body as Schedulin.RateLimitErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v0/social-accounts/{id}/next-slots",
        );
    }

    /**
     * List the boards for a connected Pinterest account. Use a board id in `platformConfiguration.board_ids` when creating a Pinterest post.
     *
     * @param {Schedulin.PinterestBoardsSocialAccountsRequest} request
     * @param {SocialAccountsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.BadRequestError}
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.ForbiddenError}
     * @throws {@link Schedulin.NotFoundError}
     * @throws {@link Schedulin.UnprocessableEntityError}
     * @throws {@link Schedulin.TooManyRequestsError}
     * @throws {@link Schedulin.InternalServerError}
     * @throws {@link errors.SchedulinError}
     * @throws {@link errors.SchedulinTimeoutError}
     *
     * @example
     *     await client.socialAccounts.pinterestBoards({
     *         id: "id"
     *     })
     */
    public pinterestBoards(
        request: Schedulin.PinterestBoardsSocialAccountsRequest,
        requestOptions?: SocialAccountsClient.RequestOptions,
    ): core.HttpResponsePromise<Schedulin.PinterestBoardsSocialAccountsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__pinterestBoards(request, requestOptions));
    }

    private async __pinterestBoards(
        request: Schedulin.PinterestBoardsSocialAccountsRequest,
        requestOptions?: SocialAccountsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Schedulin.PinterestBoardsSocialAccountsResponse>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                `v0/social-accounts/${core.url.encodePathParam(id)}/pinterest-boards`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Schedulin.PinterestBoardsSocialAccountsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Schedulin.BadRequestError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Schedulin.ForbiddenError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Schedulin.NotFoundError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new Schedulin.UnprocessableEntityError(
                        _response.error.body as Schedulin.ValidationErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Schedulin.TooManyRequestsError(
                        _response.error.body as Schedulin.RateLimitErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v0/social-accounts/{id}/pinterest-boards",
        );
    }

    /**
     * Fetch the privacy-level options, duration limits, and interaction settings for a connected TikTok account — required to build a valid `platformConfiguration` when creating a TikTok post.
     *
     * @param {Schedulin.TiktokCreatorInfoSocialAccountsRequest} request
     * @param {SocialAccountsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.BadRequestError}
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.ForbiddenError}
     * @throws {@link Schedulin.NotFoundError}
     * @throws {@link Schedulin.UnprocessableEntityError}
     * @throws {@link Schedulin.TooManyRequestsError}
     * @throws {@link Schedulin.InternalServerError}
     * @throws {@link errors.SchedulinError}
     * @throws {@link errors.SchedulinTimeoutError}
     *
     * @example
     *     await client.socialAccounts.tiktokCreatorInfo({
     *         id: "id"
     *     })
     */
    public tiktokCreatorInfo(
        request: Schedulin.TiktokCreatorInfoSocialAccountsRequest,
        requestOptions?: SocialAccountsClient.RequestOptions,
    ): core.HttpResponsePromise<Schedulin.TiktokCreatorInfoSocialAccountsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__tiktokCreatorInfo(request, requestOptions));
    }

    private async __tiktokCreatorInfo(
        request: Schedulin.TiktokCreatorInfoSocialAccountsRequest,
        requestOptions?: SocialAccountsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Schedulin.TiktokCreatorInfoSocialAccountsResponse>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                `v0/social-accounts/${core.url.encodePathParam(id)}/tiktok-creator-info`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Schedulin.TiktokCreatorInfoSocialAccountsResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Schedulin.BadRequestError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 403:
                    throw new Schedulin.ForbiddenError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 404:
                    throw new Schedulin.NotFoundError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 422:
                    throw new Schedulin.UnprocessableEntityError(
                        _response.error.body as Schedulin.ValidationErrorResponse,
                        _response.rawResponse,
                    );
                case 429:
                    throw new Schedulin.TooManyRequestsError(
                        _response.error.body as Schedulin.RateLimitErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v0/social-accounts/{id}/tiktok-creator-info",
        );
    }
}
