// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         url: "url",
 *         events: ["post.published"]
 *     }
 */
export interface CreateWebhooksRequest {
    url: string;
    events: CreateWebhooksRequest.Events.Item[];
    description?: string;
}

export namespace CreateWebhooksRequest {
    export type Events = Events.Item[];

    export namespace Events {
        export const Item = {
            PostPublished: "post.published",
            PostFailed: "post.failed",
            GenerationCompleted: "generation.completed",
            GenerationFailed: "generation.failed",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }
}
