// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface ListDeliveriesWebhooksRequest {
    id: string;
    limit?: number;
    page?: number;
}
