// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface UpdateWebhooksRequest {
    id: string;
    url?: string;
    events?: UpdateWebhooksRequest.Events.Item[];
    description?: string | null;
    enabled?: boolean;
}

export namespace UpdateWebhooksRequest {
    export type Events = Events.Item[];

    export namespace Events {
        export const Item = {
            PostPublished: "post.published",
            PostFailed: "post.failed",
            GenerationCompleted: "generation.completed",
            GenerationFailed: "generation.failed",
        } as const;
        export type Item = (typeof Item)[keyof typeof Item];
    }
}
