// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         prompt: "prompt"
 *     }
 */
export interface GenerateImageAiRequest {
    prompt: string;
    modelKey?: GenerateImageAiRequest.ModelKey;
    width?: number;
    height?: number;
}

export namespace GenerateImageAiRequest {
    export const ModelKey = {
        FluxSchnell: "flux_schnell",
        FluxDev: "flux_dev",
        FluxProUltra: "flux_pro_ultra",
    } as const;
    export type ModelKey = (typeof ModelKey)[keyof typeof ModelKey];
}
