// This file was auto-generated by Fern from our API Definition.

import type * as Schedulin from "../../../index.js";

export interface AnalyticsSeriesPostsResponse {
    data: AnalyticsSeriesPostsResponse.Data.Item[];
}

export namespace AnalyticsSeriesPostsResponse {
    export type Data = Data.Item[];

    export namespace Data {
        export interface Item {
            id: string;
            collectedAt: string;
            platform: Schedulin.SocialPlatform;
            metrics?: (unknown | null) | undefined;
        }
    }
}
