// This file was auto-generated by Fern from our API Definition.

export interface AnalyticsSummaryPostsResponse {
    analyticsLatest?: (unknown | null) | undefined;
    analyticsLastFetchedAt: string | null;
    analyticsNextFetchAt: string | null;
    updatedAt: string;
}
