// This file was auto-generated by Fern from our API Definition.

import type * as Schedulin from "../../../index.js";

export interface AnalyticsSeriesPostsResponseItem {
    id: string;
    collectedAt: string;
    platform: Schedulin.SocialPlatform;
    metrics?: (unknown | null) | undefined;
}
