// This file was auto-generated by Fern from our API Definition.

export const ListPostsRequestStatusesItem = {
    Scheduled: "SCHEDULED",
    Processing: "PROCESSING",
    Completed: "COMPLETED",
    Draft: "DRAFT",
    Failed: "FAILED",
} as const;
export type ListPostsRequestStatusesItem =
    (typeof ListPostsRequestStatusesItem)[keyof typeof ListPostsRequestStatusesItem];
