// This file was auto-generated by Fern from our API Definition.

export const ListPostsRequestApprovalStatus = {
    Draft: "DRAFT",
    PendingApproval: "PENDING_APPROVAL",
    Approved: "APPROVED",
    Rejected: "REJECTED",
} as const;
export type ListPostsRequestApprovalStatus =
    (typeof ListPostsRequestApprovalStatus)[keyof typeof ListPostsRequestApprovalStatus];
