// This file was auto-generated by Fern from our API Definition.

export const ListPostsRequestTagMode = {
    Any: "ANY",
    All: "ALL",
} as const;
export type ListPostsRequestTagMode = (typeof ListPostsRequestTagMode)[keyof typeof ListPostsRequestTagMode];
