// This file was auto-generated by Fern from our API Definition.

export const ListPostsRequestStatus = {
    Scheduled: "SCHEDULED",
    Processing: "PROCESSING",
    Completed: "COMPLETED",
    Draft: "DRAFT",
    Failed: "FAILED",
} as const;
export type ListPostsRequestStatus = (typeof ListPostsRequestStatus)[keyof typeof ListPostsRequestStatus];
