// This file was auto-generated by Fern from our API Definition.

import type * as Schedulin from "../../../index.js";

export interface ListPostsResponse {
    posts: Schedulin.PostWithRelations[];
    page: number;
    totalPages: number;
    total: number;
}
