// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import { mergeAdditionalBodyParameters } from "../../../../core/requestBody.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Schedulin from "../../../index.js";

export declare namespace WebhooksClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class WebhooksClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<WebhooksClient.Options>;

    constructor(options: WebhooksClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * List the organization's webhook endpoints. Signing secrets are masked.
     *
     * @param {WebhooksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.InternalServerError}
     * @throws {@link errors.SchedulinError}
     * @throws {@link errors.SchedulinTimeoutError}
     *
     * @example
     *     await client.webhooks.list()
     */
    public list(requestOptions?: WebhooksClient.RequestOptions): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__list(requestOptions));
    }

    private async __list(requestOptions?: WebhooksClient.RequestOptions): Promise<core.WithRawResponse<unknown>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                "v0/webhooks",
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v0/webhooks");
    }

    /**
     * Register an HTTPS endpoint for event deliveries. The response includes the signing secret ONCE — store it; later reads return a masked value.
     *
     * @param {Schedulin.CreateWebhooksRequest} request
     * @param {WebhooksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.InternalServerError}
     * @throws {@link errors.SchedulinError}
     * @throws {@link errors.SchedulinTimeoutError}
     *
     * @example
     *     await client.webhooks.create({
     *         url: "url",
     *         events: ["post.published"]
     *     })
     */
    public create(
        request: Schedulin.CreateWebhooksRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__create(request, requestOptions));
    }

    private async __create(
        request: Schedulin.CreateWebhooksRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                "v0/webhooks",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(request, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v0/webhooks");
    }

    /**
     * Retrieve one webhook endpoint, including failure counters. The signing secret is masked.
     *
     * @param {Schedulin.RetrieveWebhooksRequest} request
     * @param {WebhooksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.InternalServerError}
     * @throws {@link errors.SchedulinError}
     * @throws {@link errors.SchedulinTimeoutError}
     *
     * @example
     *     await client.webhooks.retrieve({
     *         id: "id"
     *     })
     */
    public retrieve(
        request: Schedulin.RetrieveWebhooksRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__retrieve(request, requestOptions));
    }

    private async __retrieve(
        request: Schedulin.RetrieveWebhooksRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                `v0/webhooks/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v0/webhooks/{id}");
    }

    /**
     * Delete a webhook endpoint and its delivery history. Deliveries already in flight are dropped.
     *
     * @param {Schedulin.DeleteWebhooksRequest} request
     * @param {WebhooksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.InternalServerError}
     * @throws {@link errors.SchedulinError}
     * @throws {@link errors.SchedulinTimeoutError}
     *
     * @example
     *     await client.webhooks.delete({
     *         id: "id"
     *     })
     */
    public delete(
        request: Schedulin.DeleteWebhooksRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__delete(request, requestOptions));
    }

    private async __delete(
        request: Schedulin.DeleteWebhooksRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                `v0/webhooks/${core.url.encodePathParam(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/v0/webhooks/{id}");
    }

    /**
     * Update URL, subscribed events, description, or enabled state. Re-enabling resets the failure streak.
     *
     * @param {Schedulin.UpdateWebhooksRequest} request
     * @param {WebhooksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.InternalServerError}
     * @throws {@link errors.SchedulinError}
     * @throws {@link errors.SchedulinTimeoutError}
     *
     * @example
     *     await client.webhooks.update({
     *         id: "id"
     *     })
     */
    public update(
        request: Schedulin.UpdateWebhooksRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__update(request, requestOptions));
    }

    private async __update(
        request: Schedulin.UpdateWebhooksRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                `v0/webhooks/${core.url.encodePathParam(id)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PATCH", "/v0/webhooks/{id}");
    }

    /**
     * Generate a new signing secret for the endpoint and return it ONCE. The old secret stops signing immediately.
     *
     * @param {Schedulin.RotateSecretWebhooksRequest} request
     * @param {WebhooksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.InternalServerError}
     * @throws {@link errors.SchedulinError}
     * @throws {@link errors.SchedulinTimeoutError}
     *
     * @example
     *     await client.webhooks.rotateSecret({
     *         id: "id"
     *     })
     */
    public rotateSecret(
        request: Schedulin.RotateSecretWebhooksRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__rotateSecret(request, requestOptions));
    }

    private async __rotateSecret(
        request: Schedulin.RotateSecretWebhooksRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                `v0/webhooks/${core.url.encodePathParam(id)}/rotate-secret`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v0/webhooks/{id}/rotate-secret",
        );
    }

    /**
     * Send a signed `ping` event to the endpoint URL and record it in the delivery history.
     *
     * @param {Schedulin.TestWebhooksRequest} request
     * @param {WebhooksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.InternalServerError}
     * @throws {@link errors.SchedulinError}
     * @throws {@link errors.SchedulinTimeoutError}
     *
     * @example
     *     await client.webhooks.test({
     *         id: "id"
     *     })
     */
    public test(
        request: Schedulin.TestWebhooksRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__test(request, requestOptions));
    }

    private async __test(
        request: Schedulin.TestWebhooksRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { id, ..._body } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                `v0/webhooks/${core.url.encodePathParam(id)}/test`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: mergeAdditionalBodyParameters(_body, requestOptions?.additionalBodyParameters),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v0/webhooks/{id}/test");
    }

    /**
     * Delivery history for a webhook endpoint: event, status, attempts, last response code, and payload.
     *
     * @param {Schedulin.ListDeliveriesWebhooksRequest} request
     * @param {WebhooksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Schedulin.UnauthorizedError}
     * @throws {@link Schedulin.InternalServerError}
     * @throws {@link errors.SchedulinError}
     * @throws {@link errors.SchedulinTimeoutError}
     *
     * @example
     *     await client.webhooks.listDeliveries({
     *         id: "id"
     *     })
     */
    public listDeliveries(
        request: Schedulin.ListDeliveriesWebhooksRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__listDeliveries(request, requestOptions));
    }

    private async __listDeliveries(
        request: Schedulin.ListDeliveriesWebhooksRequest,
        requestOptions?: WebhooksClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { id, limit, page } = request;
        const _queryParams: Record<string, unknown> = {
            limit,
            page,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SchedulinEnvironment.Default,
                `v0/webhooks/${core.url.encodePathParam(id)}/deliveries`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url
                .queryBuilder()
                .addMany(_queryParams)
                .mergeAdditional(requestOptions?.queryParams)
                .build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Schedulin.UnauthorizedError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                case 500:
                    throw new Schedulin.InternalServerError(
                        _response.error.body as Schedulin.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SchedulinError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v0/webhooks/{id}/deliveries");
    }
}
