// This file was auto-generated by Fern from our API Definition.

export interface ListSocialAccountsResponseItem {
    id: string;
    platform: ListSocialAccountsResponseItem.Platform;
    status: ListSocialAccountsResponseItem.Status;
    username: string | null;
    displayName: string | null;
    profileImageUrl: string | null;
    refreshTokenValid: boolean;
    analyticsDisabledAt: string | null;
    createdAt: string;
    updatedAt: string;
}

export namespace ListSocialAccountsResponseItem {
    export const Platform = {
        Bluesky: "bluesky",
        Facebook: "facebook",
        Instagram: "instagram",
        Linkedin: "linkedin",
        Pinterest: "pinterest",
        Threads: "threads",
        Tiktok: "tiktok",
        Twitter: "twitter",
        Youtube: "youtube",
    } as const;
    export type Platform = (typeof Platform)[keyof typeof Platform];
    export const Status = {
        Connected: "connected",
        Disconnected: "disconnected",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
