// This file was auto-generated by Fern from our API Definition.

export interface ListSlackChannelsSocialAccountsResponse {
    items: ListSlackChannelsSocialAccountsResponse.Items.Item[];
}

export namespace ListSlackChannelsSocialAccountsResponse {
    export type Items = Items.Item[];

    export namespace Items {
        export interface Item {
            id: string;
            name: string;
        }
    }
}
