// This file was auto-generated by Fern from our API Definition.

export interface ListWhopCompaniesSocialAccountsResponse {
    items: ListWhopCompaniesSocialAccountsResponse.Items.Item[];
}

export namespace ListWhopCompaniesSocialAccountsResponse {
    export type Items = Items.Item[];

    export namespace Items {
        export interface Item {
            id: string;
            name: string;
        }
    }
}
