// This file was auto-generated by Fern from our API Definition.

export interface ListWhopForumsSocialAccountsResponse {
    items: ListWhopForumsSocialAccountsResponse.Items.Item[];
}

export namespace ListWhopForumsSocialAccountsResponse {
    export type Items = Items.Item[];

    export namespace Items {
        export interface Item {
            id: string;
            name: string;
        }
    }
}
