// This file was auto-generated by Fern from our API Definition.

export interface ListDiscordChannelsSocialAccountsResponse {
    items: ListDiscordChannelsSocialAccountsResponse.Items.Item[];
}

export namespace ListDiscordChannelsSocialAccountsResponse {
    export type Items = Items.Item[];

    export namespace Items {
        export interface Item {
            id: string;
            name: string;
        }
    }
}
