// This file was auto-generated by Fern from our API Definition.

export interface ListSocialAccountsResponse {
    data: ListSocialAccountsResponse.Data.Item[];
}

export namespace ListSocialAccountsResponse {
    export type Data = Data.Item[];

    export namespace Data {
        export interface Item {
            id: string;
            platform: Item.Platform;
            status: Item.Status;
            username: string | null;
            displayName: string | null;
            profileImageUrl: string | null;
            refreshTokenValid: boolean;
            analyticsDisabledAt: string | null;
            createdAt: string;
            updatedAt: string;
        }

        export namespace Item {
            export const Platform = {
                Bluesky: "bluesky",
                Facebook: "facebook",
                GoogleBusinessProfile: "google_business_profile",
                Instagram: "instagram",
                Linkedin: "linkedin",
                Pinterest: "pinterest",
                Reddit: "reddit",
                Threads: "threads",
                Tiktok: "tiktok",
                Twitter: "twitter",
                Youtube: "youtube",
            } as const;
            export type Platform = (typeof Platform)[keyof typeof Platform];
            export const Status = {
                Connected: "connected",
                Disconnected: "disconnected",
            } as const;
            export type Status = (typeof Status)[keyof typeof Status];
        }
    }
}
