// This file was auto-generated by Fern from our API Definition.

export interface PinterestBoardsSocialAccountsResponse {
    data: PinterestBoardsSocialAccountsResponse.Data.Item[];
}

export namespace PinterestBoardsSocialAccountsResponse {
    export type Data = Data.Item[];

    export namespace Data {
        export interface Item {
            id: string;
            name: string;
            privacy?: Item.Privacy | undefined;
        }

        export namespace Item {
            export const Privacy = {
                Public: "PUBLIC",
                Protected: "PROTECTED",
                Secret: "SECRET",
            } as const;
            export type Privacy = (typeof Privacy)[keyof typeof Privacy];
        }
    }
}
