// This file was auto-generated by Fern from our API Definition.

export interface RefreshProfileSocialAccountsResponse {
    success: boolean;
    username?: (string | null) | undefined;
    imageUrl?: (string | null) | undefined;
    name?: (string | null) | undefined;
}
