// This file was auto-generated by Fern from our API Definition.

export interface TiktokCreatorInfoSocialAccountsResponse {
    error: TiktokCreatorInfoSocialAccountsResponse.Error_;
    data: TiktokCreatorInfoSocialAccountsResponse.Data;
}

export namespace TiktokCreatorInfoSocialAccountsResponse {
    export interface Error_ {
        code: string;
        message: string;
        log_id: string;
    }

    export interface Data {
        creator_avatar_url: string;
        creator_username: string;
        creator_nickname: string;
        privacy_level_options: string[];
        comment_disabled: boolean;
        duet_disabled: boolean;
        stitch_disabled: boolean;
        max_video_post_duration_sec: number;
    }
}
