// This file was auto-generated by Fern from our API Definition.

export interface CountByTagMediaResponse {
    data: CountByTagMediaResponse.Data.Item[];
}

export namespace CountByTagMediaResponse {
    export type Data = Data.Item[];

    export namespace Data {
        export interface Item {
            tagId: string;
            count: number;
        }
    }
}
