// This file was auto-generated by Fern from our API Definition.

export const ListMediaRequestTagMode = {
    Any: "ANY",
    All: "ALL",
} as const;
export type ListMediaRequestTagMode = (typeof ListMediaRequestTagMode)[keyof typeof ListMediaRequestTagMode];
