// This file was auto-generated by Fern from our API Definition.

import type * as Schedulin from "../../../index.js";

export interface ListMediaResponse {
    items: Schedulin.Media[];
    page: number;
    total: number;
    totalPages: number;
}
