// This file was auto-generated by Fern from our API Definition.

export const ListMediaRequestType = {
    Image: "image",
    Video: "video",
    All: "all",
} as const;
export type ListMediaRequestType = (typeof ListMediaRequestType)[keyof typeof ListMediaRequestType];
