// This file was auto-generated by Fern from our API Definition.

export interface ListMediaRequestCursor {
    id: string;
    updatedAt: ListMediaRequestCursor.UpdatedAt;
}

export namespace ListMediaRequestCursor {
    export type UpdatedAt = string | string;
}
